/**
 * Index 部件模型
 *
 * @export
 * @class IndexModel
 */
export default class IndexModel {

    /**
     * 菜单项集合
     *
     * @public
     * @type {any[]}
     * @memberof IndexModel
     */
    public items: any[] = [
        {
	id: 'E889CC85-4929-4A4B-AC8A-BD25EAE4360C',
	name: 'menuitem1',
	text: '基础数据',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '基础数据',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/gongzidanmingxi.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem1',
	items: [
		{
	id: 'C25FBF7B-A076-44AF-A5C5-8FEE247C28FB',
	name: 'menuitem2',
	text: '薪酬类型',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬类型',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/gongzidanmingxi.png',
	textcls: '',
	appfunctag: 'Auto71',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem2',
},
		{
	id: '57943DDD-3E1F-4796-939E-CB3906CF1E16',
	name: 'menuitem3',
	text: '薪酬计算源',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬计算源',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xinchoujisuanyuan.png',
	textcls: '',
	appfunctag: 'Auto53',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem3',
},
		{
	id: '39A731AF-766B-4AE0-8762-019277A8789A',
	name: 'menuitem4',
	text: '薪酬计算指标',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬计算指标',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xinchoujisuanzhibiao.png',
	textcls: '',
	appfunctag: 'Auto51',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem4',
},
		{
	id: '1B95461E-E287-4883-8821-67E436708D7E',
	name: 'menuitem5',
	text: '薪酬规则',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬规则',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xinchoukemu.png',
	textcls: '',
	appfunctag: 'Auto49',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem5',
},
		{
	id: 'BF32A34B-2291-4E92-A0E3-76D88D6FD723',
	name: 'menuitem6',
	text: '薪酬要素项',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬要素项',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xinchoujisuanyaosu.png',
	textcls: '',
	appfunctag: 'Auto81',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem6',
},
		{
	id: '8FC8C8D8-37F1-462F-8E0A-B5BE483E6E0A',
	name: 'menuitem7',
	text: '工资单',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '工资单',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xinchoujisuanfangan.png',
	textcls: '',
	appfunctag: 'Auto59',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem7',
},
	],
},
        {
	id: '41A41BBE-C956-4BAF-884D-1F77D53BA0CD',
	name: 'menuitem8',
	text: '薪酬标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬标准',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/gangweigongzibiaozhun.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem8',
	items: [
		{
	id: '56318EA7-CB74-4D1A-B8FF-D749C66AE967',
	name: 'menuitem11',
	text: '岗位工资标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '岗位工资标准',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/gangweigongzibiaozhun.png',
	textcls: '',
	appfunctag: 'Auto65',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem11',
},
		{
	id: '921750BF-AF6C-4175-B973-666AFB5254D2',
	name: 'menuitem12',
	text: '项目工资标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '项目工资标准',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xiangmugongzibiaozhun.png',
	textcls: '',
	appfunctag: 'Auto52',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem12',
},
		{
	id: '5E528C3D-FD43-48C9-AB67-9814C2D3FF22',
	name: 'menuitem13',
	text: '工龄工资标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '工龄工资标准',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/gonglinggongzibiaozhun.png',
	textcls: '',
	appfunctag: 'Auto48',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem13',
},
		{
	id: '7B737593-FBA0-4E5D-A534-6F604B3387C0',
	name: 'menuitem14',
	text: '技术津贴标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '技术津贴标准',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/zhichengjintiebiaozhun.png',
	textcls: '',
	appfunctag: 'Auto61',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem14',
},
		{
	id: '5F07430B-3F82-4674-B9D2-2FFE68835B9C',
	name: 'menuitem15',
	text: '专项津贴标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '专项津贴标准',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/zhuanxiangjintiebiaozhun.png',
	textcls: '',
	appfunctag: 'Auto54',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem15',
},
		{
	id: 'DEBD79BD-01D5-4316-B0C4-21A024BD86CC',
	name: 'menuitem21',
	text: '执业资格津贴标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '执业资格津贴标准',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/zhiyezigejintiebiaozhun.png',
	textcls: '',
	appfunctag: 'Auto66',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem21',
},
		{
	id: '96A86E0D-B895-441A-900D-ADCFD3098BB1',
	name: 'menuitem22',
	text: '独生子女津贴标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '独生子女津贴标准',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/dushengzinvbiaozhun.png',
	textcls: '',
	appfunctag: 'Auto62',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem22',
},
		{
	id: 'CDC934DD-3B69-4FC4-87E8-6C36D3FB2608',
	name: 'menuitem23',
	text: '高温津贴标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '高温津贴标准',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/gaowenjintiebiaozhun.png',
	textcls: '',
	appfunctag: 'Auto69',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem23',
},
	],
},
        {
	id: 'AFB0BBF0-430C-4939-94B4-6917C2CB6C4F',
	name: 'menuitem9',
	text: '员工薪酬档案',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '员工薪酬档案',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/yuangongxinchoubiaozhun.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem9',
	items: [
		{
	id: '7FBEC704-275B-4114-B907-C7D3C907CA11',
	name: 'menuitem16',
	text: '员工薪酬档案',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '员工薪酬档案',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/yuangongxinchoubiaozhun.png',
	textcls: '',
	appfunctag: 'Auto74',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem16',
},
		{
	id: 'D27E5F3D-D3F9-4723-8C37-3D781E964A5E',
	name: 'menuitem17',
	text: '员工薪酬档案确认',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '员工薪酬档案确认',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/yuangongxinchoubiaozhunqueren.png',
	textcls: '',
	appfunctag: 'Auto74',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem17',
},
	],
},
        {
	id: '3D8B95B5-F126-40FC-B1D0-B8B2824E5590',
	name: 'menuitem10',
	text: '薪酬管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬管理',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xinchoujisuanjihua.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem10',
	items: [
		{
	id: '12BEC382-C049-4BD0-AF91-3CBEA6FFBA09',
	name: 'menuitem18',
	text: '薪酬计算计划',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬计算计划',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xinchoujisuanjihua.png',
	textcls: '',
	appfunctag: 'Auto55',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem18',
},
		{
	id: '928486F3-2A58-43F2-9A48-5EB8F3B2508C',
	name: 'menuitem19',
	text: '员工工资',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '员工工资',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jcgl/1/xinchouxinxi.png',
	textcls: '',
	appfunctag: 'Auto60',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem19',
},
		{
	id: 'C577431A-FACE-4EA1-8106-214B5E978883',
	name: 'menuitem20',
	text: '薪酬调整日志',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '薪酬调整日志',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jcgl/1/lunwenxinxi.png',
	textcls: '',
	appfunctag: 'Auto77',
	resourcetag: '',
	authtag:'EHRSal-Index-menuitem20',
},
	],
},
    ];

	/**
	 * 应用功能集合
	 *
	 * @public
	 * @type {any[]}
	 * @memberof IndexModel
	 */
	public funcs: any[] = [
        {
            appfunctag: 'Auto81',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salitemgridview',
            deResParameters: [],
            routepath: '/index/:index?/salitems/:salitem?/gridview/:gridview?',
            parameters: [
                { pathName: 'salitems', parameterName: 'salitem' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto60',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salsalarygridview',
            deResParameters: [],
            routepath: '/index/:index?/salsalaries/:salsalary?/gridview/:gridview?',
            parameters: [
                { pathName: 'salsalaries', parameterName: 'salsalary' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto54',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salstdzxgridview',
            deResParameters: [],
            routepath: '/index/:index?/salstdzxes/:salstdzx?/gridview/:gridview?',
            parameters: [
                { pathName: 'salstdzxes', parameterName: 'salstdzx' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto77',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salloggridview',
            deResParameters: [],
            routepath: '/index/:index?/sallogs/:sallog?/gridview/:gridview?',
            parameters: [
                { pathName: 'sallogs', parameterName: 'sallog' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto71',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'saltypegridview',
            deResParameters: [],
            routepath: '/index/:index?/saltypes/:saltype?/gridview/:gridview?',
            parameters: [
                { pathName: 'saltypes', parameterName: 'saltype' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto51',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salparamgridview',
            deResParameters: [],
            routepath: '/index/:index?/salparams/:salparam?/gridview/:gridview?',
            parameters: [
                { pathName: 'salparams', parameterName: 'salparam' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto69',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salstdgwgridview',
            deResParameters: [],
            routepath: '/index/:index?/salstdgws/:salstdgw?/gridview/:gridview?',
            parameters: [
                { pathName: 'salstdgws', parameterName: 'salstdgw' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto59',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salschemegridview',
            deResParameters: [],
            routepath: '/index/:index?/salschemes/:salscheme?/gridview/:gridview?',
            parameters: [
                { pathName: 'salschemes', parameterName: 'salscheme' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto66',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salstdzyzggridview',
            deResParameters: [],
            routepath: '/index/:index?/salstdzyzgs/:salstdzyzg?/gridview/:gridview?',
            parameters: [
                { pathName: 'salstdzyzgs', parameterName: 'salstdzyzg' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto55',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salplangridview',
            deResParameters: [],
            routepath: '/index/:index?/salplans/:salplan?/gridview/:gridview?',
            parameters: [
                { pathName: 'salplans', parameterName: 'salplan' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto61',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salstdzcgridview',
            deResParameters: [],
            routepath: '/index/:index?/salstdzcs/:salstdzc?/gridview/:gridview?',
            parameters: [
                { pathName: 'salstdzcs', parameterName: 'salstdzc' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto65',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salstdgwgzgridview',
            deResParameters: [],
            routepath: '/index/:index?/salstdgwgzs/:salstdgwgz?/gridview/:gridview?',
            parameters: [
                { pathName: 'salstdgwgzs', parameterName: 'salstdgwgz' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto53',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salsourcegridview',
            deResParameters: [],
            routepath: '/index/:index?/salsources/:salsource?/gridview/:gridview?',
            parameters: [
                { pathName: 'salsources', parameterName: 'salsource' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto74',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salpersonstdgridview',
            deResParameters: [],
            routepath: '/index/:index?/salpersonstds/:salpersonstd?/gridview/:gridview?',
            parameters: [
                { pathName: 'salpersonstds', parameterName: 'salpersonstd' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto52',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salstdxmgzgridview',
            deResParameters: [],
            routepath: '/index/:index?/salstdxmgzs/:salstdxmgz?/gridview/:gridview?',
            parameters: [
                { pathName: 'salstdxmgzs', parameterName: 'salstdxmgz' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto62',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salstddszngridview',
            deResParameters: [],
            routepath: '/index/:index?/salstddszns/:salstddszn?/gridview/:gridview?',
            parameters: [
                { pathName: 'salstddszns', parameterName: 'salstddszn' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto48',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salstdglgridview',
            deResParameters: [],
            routepath: '/index/:index?/salstdgls/:salstdgl?/gridview/:gridview?',
            parameters: [
                { pathName: 'salstdgls', parameterName: 'salstdgl' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto49',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'salrulegridview',
            deResParameters: [],
            routepath: '/index/:index?/salrules/:salrule?/gridview/:gridview?',
            parameters: [
                { pathName: 'salrules', parameterName: 'salrule' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
	];

    /**
     * 获取所有菜单项集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppMenuItems(): any[] {
        return this.items;
    }

    /**
     * 获取所有应用功能集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppFuncs(): any[] {
        return this.funcs;
    }
}