/**
 * Index 部件模型
 *
 * @export
 * @class IndexModel
 */
export default class IndexModel {

    /**
     * 菜单项集合
     *
     * @public
     * @type {any[]}
     * @memberof IndexModel
     */
    public items: any[] = [
        {
	id: 'ED0C5606-4F3E-4CBD-8CF7-1ABC0E26DAB8',
	name: 'menuitem1',
	text: '培训资源',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训资源',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jcgl/1/danganguanli.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem1',
	items: [
		{
	id: 'CC85A158-6FAC-4412-AF7B-7C31F0F95D22',
	name: 'menuitem6',
	text: '培训机构',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训机构',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/peixunjigou.png',
	textcls: '',
	appfunctag: '_17',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem6',
},
		{
	id: '314D5184-58EA-4F87-8D4E-9E94A47E12AA',
	name: 'menuitem7',
	text: '培训场地',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训场地',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunsheshi.png',
	textcls: '',
	appfunctag: '_5',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem7',
},
		{
	id: 'CEF509A4-7C06-4213-B7A8-28F7D8218B6B',
	name: 'menuitem8',
	text: '培训模块',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训模块',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunziliao.png',
	textcls: '',
	appfunctag: '_3',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem8',
},
		{
	id: 'E23C028D-99A7-4F64-ACC9-3046CB6C5678',
	name: 'menuitem9',
	text: '培训课程',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训课程',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunkecheng.png',
	textcls: '',
	appfunctag: '_18',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem9',
},
		{
	id: 'DD704CB1-88A1-45E6-B6D0-C1F4C2C54DE4',
	name: 'menuitem10',
	text: '内部讲师',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '内部讲师',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/pzgl/1/chengshurencaizhaopin.png',
	textcls: '',
	appfunctag: '_13',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem10',
},
		{
	id: 'DC1B55EF-1F38-44F1-93B1-3BFE7A38F7F3',
	name: 'menuitem11',
	text: '外部讲师',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '外部讲师',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/pzgl/1/xiaoyuanzhaopin.png',
	textcls: '',
	appfunctag: '_16',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem11',
},
	],
},
        {
	id: 'DCD854A9-8112-48BC-A69F-CD487F758AF1',
	name: 'menuitem2',
	text: '培训需求',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训需求',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jcgl/1/danganxinxi.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem2',
	items: [
		{
	id: '57392FF2-9B84-4192-A37F-1974EFD2305B',
	name: 'menuitem12',
	text: '需求通知',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '需求通知',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/yuangongxuqiutianbao.png',
	textcls: '',
	appfunctag: '_4',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem12',
},
		{
	id: 'C5FC6E19-31DB-4EE6-A78D-4F0440A58704',
	name: 'menuitem13',
	text: '需求填报',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '需求填报',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/xuqiudiaochadingyi.png',
	textcls: '',
	appfunctag: '_11',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem13',
},
	],
},
        {
	id: '5679BCE0-996A-4452-9BA0-11F3105680C4',
	name: 'menuitem3',
	text: '培训计划',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训计划',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunjihua.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem3',
	items: [
		{
	id: '0ECEFBEE-C893-4C89-B418-2701707F433F',
	name: 'menuitem15',
	text: '计划制定',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '计划制定',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunjihua.png',
	textcls: '',
	appfunctag: '_7',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem15',
},
		{
	id: '136D91F9-4565-4DE1-9264-2A281EAC99A7',
	name: 'menuitem16',
	text: '计划审批',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '计划审批',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/gongsipenxunjihuazhiding.png',
	textcls: '',
	appfunctag: '_6',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem16',
},
		{
	id: '39B1BF6E-4928-4697-8BA0-6D5A48319F27',
	name: 'menuitem17',
	text: '计划发布',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '计划发布',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/bumenxuqiutianbao.png',
	textcls: '',
	appfunctag: '_8',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem17',
},
		{
	id: 'CD5B5D2D-E4E8-4182-9D17-BAC270F315C1',
	name: 'menuitem22',
	text: '外出培训申请',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '外出培训申请',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/waibupeixunshenqing.png',
	textcls: '',
	appfunctag: '_9',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem22',
},
	],
},
        {
	id: 'A061D949-6007-47CE-BFBC-2DFCABF34736',
	name: 'menuitem4',
	text: '培训实施',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训实施',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/lianghuamubiaokaohe.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem4',
	items: [
		{
	id: '7B1F144E-3EEA-4ABC-97CD-2931C633D22C',
	name: 'menuitem18',
	text: '培训立项',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训立项',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunhuodong.png',
	textcls: '',
	appfunctag: '_19',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem18',
},
		{
	id: '620E3910-0B2D-441B-89D2-81ECF767E9C7',
	name: 'menuitem19',
	text: '培训班级',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训班级',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunhuodongshenqing.png',
	textcls: '',
	appfunctag: '_15',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem19',
},
		{
	id: '4DF69405-DE98-489E-AEA8-C062DCC4CBC4',
	name: 'menuitem20',
	text: '培训后评估',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训后评估',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jxgl/1/jixiaokaohepinggu.png',
	textcls: '',
	appfunctag: '_10',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem20',
},
	],
},
        {
	id: '39657408-8010-4B72-90D0-107316272729',
	name: 'menuitem5',
	text: '培训费用',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训费用',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunyusuan.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem5',
	items: [
		{
	id: 'DB67E1CA-BB14-418E-9C7C-136C64F15861',
	name: 'menuitem23',
	text: '培训费用登记',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '培训费用登记',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunyusuanshenqing.png',
	textcls: '',
	appfunctag: '_14',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem23',
},
		{
	id: 'A4093CC5-F4D5-45E1-9C64-84438442FAD6',
	name: 'menuitem21',
	text: '讲师费用登记',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '讲师费用登记',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xinchoujisuanzhibiao.png',
	textcls: '',
	appfunctag: '_2',
	resourcetag: '',
	authtag:'EHRTrm-Index-menuitem21',
},
	],
},
    ];

	/**
	 * 应用功能集合
	 *
	 * @public
	 * @type {any[]}
	 * @memberof IndexModel
	 */
	public funcs: any[] = [
        {
            appfunctag: '_7',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmplanformugridview',
            deResParameters: [],
            routepath: '/index/:index?/trmplanformus/:trmplanformu?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmplanformus', parameterName: 'trmplanformu' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_6',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainplanfgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainplans/:trmtrainplan?/fgridview/:fgridview?',
            parameters: [
                { pathName: 'trmtrainplans', parameterName: 'trmtrainplan' },
                { pathName: 'fgridview', parameterName: 'fgridview' },
            ],
        },
        {
            appfunctag: '_14',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainbuapplygridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainbuapplies/:trmtrainbuapply?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtrainbuapplies', parameterName: 'trmtrainbuapply' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_5',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainaddressgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainaddresses/:trmtrainaddress?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtrainaddresses', parameterName: 'trmtrainaddress' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_16',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainteacherwbgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainteachers/:trmtrainteacher?/wbgridview/:wbgridview?',
            parameters: [
                { pathName: 'trmtrainteachers', parameterName: 'trmtrainteacher' },
                { pathName: 'wbgridview', parameterName: 'wbgridview' },
            ],
        },
        {
            appfunctag: '_11',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainfillingridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainfillins/:trmtrainfillin?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtrainfillins', parameterName: 'trmtrainfillin' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_15',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainplantermbjgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainplanterms/:trmtrainplanterm?/bjgridview/:bjgridview?',
            parameters: [
                { pathName: 'trmtrainplanterms', parameterName: 'trmtrainplanterm' },
                { pathName: 'bjgridview', parameterName: 'bjgridview' },
            ],
        },
        {
            appfunctag: '_3',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmcoursesystemgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmcoursesystems/:trmcoursesystem?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmcoursesystems', parameterName: 'trmcoursesystem' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_18',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtraincoursegridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtraincourses/:trmtraincourse?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtraincourses', parameterName: 'trmtraincourse' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_2',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmteacherchargegridview',
            deResParameters: [],
            routepath: '/index/:index?/trmteachercharges/:trmteachercharge?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmteachercharges', parameterName: 'trmteachercharge' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_10',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainactmentgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainactments/:trmtrainactment?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtrainactments', parameterName: 'trmtrainactment' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_17',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainagencygridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainagencies/:trmtrainagency?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtrainagencies', parameterName: 'trmtrainagency' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_9',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainoutapplygridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainoutapplies/:trmtrainoutapply?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtrainoutapplies', parameterName: 'trmtrainoutapply' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_19',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainplantermgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainplanterms/:trmtrainplanterm?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtrainplanterms', parameterName: 'trmtrainplanterm' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_8',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainplanjhfbgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainplans/:trmtrainplan?/jhfbgridview/:jhfbgridview?',
            parameters: [
                { pathName: 'trmtrainplans', parameterName: 'trmtrainplan' },
                { pathName: 'jhfbgridview', parameterName: 'jhfbgridview' },
            ],
        },
        {
            appfunctag: '_13',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmtrainteachergridview',
            deResParameters: [],
            routepath: '/index/:index?/trmtrainteachers/:trmtrainteacher?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmtrainteachers', parameterName: 'trmtrainteacher' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: '_4',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'trmdepartgridview',
            deResParameters: [],
            routepath: '/index/:index?/trmdeparts/:trmdepart?/gridview/:gridview?',
            parameters: [
                { pathName: 'trmdeparts', parameterName: 'trmdepart' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
	];

    /**
     * 获取所有菜单项集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppMenuItems(): any[] {
        return this.items;
    }

    /**
     * 获取所有应用功能集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppFuncs(): any[] {
        return this.funcs;
    }
}