server:
  port: 6098
#zuul网关路由设置
zuul:
  routes:
    dynachart:
      path: /dynacharts/**
      serviceId: r7rt-dyna
      stripPrefix: false
    codelist:
      path: /codelist1s/**
      serviceId: ehr-webapi
      stripPrefix: false
    partzgg:
      path: /partzggs/**
      serviceId: ehr-webapi
      stripPrefix: false
    dynadashboard:
      path: /dynadashboards/**
      serviceId: r7rt-dyna
      stripPrefix: false
    codeitem:
      path: /codeitems/**
      serviceId: ehr-webapi
      stripPrefix: false
    parexamcycle:
      path: /parexamcycles/**
      serviceId: ehr-webapi
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
