server:
  port: 6098
#Log配置
logging:
  level:
    cn.ibizlab.ehr: info
#zuul网关路由设置
zuul:
  routes:
    parjxndkhjg:
      path: /parjxndkhjgs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parfzsmx:
      path: /parfzsmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parptryndlhmbmx:
      path: /parptryndlhmbmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    dynachart:
      path: /dynacharts/**
      serviceId: r7rt-dyna
      stripPrefix: false
    parjxjg:
      path: /parjxjgs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parznbmndlhmb:
      path: /parznbmndlhmbs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parlhmbmx:
      path: /parlhmbmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parldkhqz:
      path: /parldkhqzs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parexamcontent:
      path: /parexamcontents/**
      serviceId: ehr-webapi
      stripPrefix: false
    parlhmbkhmx:
      path: /parlhmbkhmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parintegralrule:
      path: /parintegralrules/**
      serviceId: ehr-webapi
      stripPrefix: false
    parznbmndlhmbmx:
      path: /parznbmndlhmbmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parkhzcmx:
      path: /parkhzcmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxkhmb:
      path: /parjxkhmbs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxzgpcmx:
      path: /parjxzgpcmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxlhmb:
      path: /parjxlhmbs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxqdsz:
      path: /parjxqdszs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxkhmbmx:
      path: /parjxkhmbmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxmtfk:
      path: /parjxmtfks/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxzgpc:
      path: /parjxzgpcs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parldndlhmbmx:
      path: /parldndlhmbmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parydgzjh:
      path: /parydgzjhs/**
      serviceId: ehr-webapi
      stripPrefix: false
    codelist:
      path: /codelist1s/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxbzglmx:
      path: /parjxbzglmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parndlhmbkh:
      path: /parndlhmbkhs/**
      serviceId: ehr-webapi
      stripPrefix: false
    partzgg:
      path: /partzggs/**
      serviceId: ehr-webapi
      stripPrefix: false
    dynadashboard:
      path: /dynadashboards/**
      serviceId: r7rt-dyna
      stripPrefix: false
    parydgzjhmx:
      path: /parydgzjhmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimperson:
      path: /pimpeople/**
      serviceId: ehr-webapi
      stripPrefix: false
    codeitem:
      path: /codeitems/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxbzgl:
      path: /parjxbzgls/**
      serviceId: ehr-webapi
      stripPrefix: false
    parbmfzjyx:
      path: /parbmfzjyxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parznbmmx:
      path: /parznbmmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxkhjcsz:
      path: /parjxkhjcszs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parptryndlhmb:
      path: /parptryndlhmbs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parldndlhmb:
      path: /parldndlhmbs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parassesstemplate:
      path: /parassesstemplates/**
      serviceId: ehr-webapi
      stripPrefix: false
    parxmbpjbz:
      path: /parxmbpjbzs/**
      serviceId: ehr-webapi
      stripPrefix: false
    pardjbz:
      path: /pardjbzs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjgbmpjbz:
      path: /parjgbmpjbzs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjxkhxhz:
      path: /parjxkhxhzs/**
      serviceId: ehr-webapi
      stripPrefix: false
    parexamcycle:
      path: /parexamcycles/**
      serviceId: ehr-webapi
      stripPrefix: false
    parjzszpsjg:
      path: /parjzszpsjgs/**
      serviceId: ehr-webapi
      stripPrefix: false
    pardxkhnrmx:
      path: /pardxkhnrmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    parkhfa:
      path: /parkhfas/**
      serviceId: ehr-webapi
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
