server:
  port: 8080
#zuul网关路由设置
zuul:
  routes:
    pimexitandentry:
      path: /pimexitandentries/**
      serviceId: ehr-webapi
      stripPrefix: false
    wfcore:
      path: /wfcore/**
      serviceId: ibzwf-api
      stripPrefix: true
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
