server:
  port: 6096
#zuul网关路由设置
zuul:
  routes:
    dynachart:
      path: /dynacharts/**
      serviceId: r7rt-dyna
      stripPrefix: false
    dynadashboard:
      path: /dynadashboards/**
      serviceId: r7rt-dyna
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
