server:
  port: 6070
#Log配置
logging:
  level:
    cn.ibizlab.ehr: info
#zuul网关路由设置
zuul:
  routes:
    pimarchives:
      path: /pimarchives/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimdistirbution:
      path: /pimdistirbutions/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimtitle:
      path: /pimtitles/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimarchivesrecord:
      path: /pimarchivesrecords/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimeducation:
      path: /pimeducations/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimfaminfo:
      path: /pimfaminfos/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimcontract:
      path: /pimcontracts/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimrewardpunishment:
      path: /pimrewardpunishments/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimachievements:
      path: /pimachievements/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimlanguageability:
      path: /pimlanguageabilities/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimperson:
      path: /pimpeople/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmydlzmx:
      path: /pcmydlzmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimtitlecatalogue:
      path: /pimtitlecatalogues/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimqualtype:
      path: /pimqualtypes/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimworkhistory:
      path: /pimworkhistories/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimexitandentry:
      path: /pimexitandentries/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormsignorg:
      path: /ormsignorgs/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacleavedetail:
      path: /vacleavedetails/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimqualmajor:
      path: /pimqualmajors/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacleavemanage:
      path: /vacleavemanages/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormorg:
      path: /ormorgs/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormorgsector:
      path: /ormorgsectors/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimvocational:
      path: /pimvocationals/**
      serviceId: ehr-webapi
      stripPrefix: false
    wfcore:
      path: /wfcore/**
      serviceId: ibzwf-api
      stripPrefix: true
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
