spring:
  profiles:
    include: sys , ehrhelp-dev,ehrpcm2-dev,ehrmob-dev,ehrpcm-dev,ehrorm-dev,ehrpim-dev,  webapi-dev,  dev
  application:
    name: ehr
  main:
    allow-bean-definition-overriding: true

  cloud:
    nacos:
      discovery:
        register-enabled: false
  datasource:
    isSyncDBSchema: true
    username: BPMEHR
    password: 'sys'
    #url: jdbc:oracle:thin:@127.0.0.1:1521:localorcl    