spring:
  profiles:
    include: sys , ehrhelp-dev,ehrpcm2-dev,ehrmob-dev,ehrpcm-dev,ehrorm-dev,ehrpim-dev,  webapi-dev,  dev
  application:
    name: ehr
  main:
    allow-bean-definition-overriding: true