/**
 * Index 部件模型
 *
 * @export
 * @class IndexModel
 */
export default class IndexModel {

    /**
     * 菜单项集合
     *
     * @public
     * @type {any[]}
     * @memberof IndexModel
     */
    public items: any[] = [
        {
	id: '25CA303B-18BE-4073-A8EE-8A0A5EF47A16',
	name: 'menuitem1',
	text: '考勤管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考勤管理',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/kaoqinshezhi.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem1',
	items: [
		{
	id: 'AE742C5D-A723-4BB6-A448-3A263D913356',
	name: 'menuitem2',
	text: '考勤规则',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考勤规则',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/jiejiariguanli.png',
	textcls: '',
	appfunctag: 'Auto40',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem2',
},
		{
	id: '73494895-12B5-490C-A30E-4F8D1CFEF636',
	name: 'menuitem3',
	text: '考勤设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考勤设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/kaoqinshezhi.png',
	textcls: '',
	appfunctag: 'Auto45',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem3',
},
		{
	id: '400F8A17-1717-44A0-81D5-33B27F3264FD',
	name: 'menuitem4',
	text: '考勤记录',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考勤记录',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/kaoqinjilu.png',
	textcls: '',
	appfunctag: 'Auto27',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem4',
},
		{
	id: 'A9C4ED03-483D-46F8-B479-FA98B1C08733',
	name: 'menuitem5',
	text: '考勤月报',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考勤月报',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/kaoqinyuebao.png',
	textcls: '',
	appfunctag: 'Auto26',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem5',
},
		{
	id: '4399C466-BCF3-46AB-9817-7AFAF5C8A08F',
	name: 'menuitem6',
	text: '考勤汇总',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考勤汇总',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/kaoqinhuizong.png',
	textcls: '',
	appfunctag: 'Auto31',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem6',
},
		{
	id: '899EC7A0-0BEA-4943-973C-9C570C5A68FE',
	name: 'menuitem7',
	text: '员工考勤设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '员工考勤设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/pzgl/1/tuixiuguanli.png',
	textcls: '',
	appfunctag: 'Auto22',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem7',
},
		{
	id: '607C5F0B-AE47-4DC9-B5D2-0BE1612E46C6',
	name: 'menuitem8',
	text: '非员工终止考勤',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '非员工终止考勤',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/guazhidaoqiguanli.png',
	textcls: '',
	appfunctag: 'Auto35',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem8',
},
	],
},
        {
	id: '78BCB6ED-DF43-4DB6-8EC9-44311AE86779',
	name: 'menuitem9',
	text: '休假管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '休假管理',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/qingjiaguanli.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem9',
	items: [
		{
	id: 'BA927B75-E1E0-4EB8-8405-942C84E4C274',
	name: 'menuitem11',
	text: '请假管理',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '请假管理',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/qingjiaguanli.png',
	textcls: '',
	appfunctag: 'Auto43',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem11',
},
		{
	id: '7AF5135A-C7B8-4CEA-AC32-1E2B7B6CE6CA',
	name: 'menuitem12',
	text: '年休假查询',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '年休假查询',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/shengyunianjiatongji.png',
	textcls: '',
	appfunctag: 'Auto33',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem12',
},
	],
},
        {
	id: '3E9E7BB6-09BA-438C-9D04-091A51351A8E',
	name: 'menuitem10',
	text: '标准化数据设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '标准化数据设置',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/pzgl/1/xuliegangweiguanxi.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem10',
	items: [
		{
	id: '055E7E95-7554-4A9B-8544-2A7E097379BE',
	name: 'menuitem13',
	text: '休假类型',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '休假类型',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/xiujialeixing.png',
	textcls: '',
	appfunctag: 'Auto21',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem13',
},
		{
	id: '9C798278-2258-4492-9DD0-256B410DDFD8',
	name: 'menuitem14',
	text: '考勤类型',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考勤类型',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/kaoqinleixing.png',
	textcls: '',
	appfunctag: 'Auto42',
	resourcetag: '',
	authtag:'EHRAtt-Index-menuitem14',
},
	],
},
    ];

	/**
	 * 应用功能集合
	 *
	 * @public
	 * @type {any[]}
	 * @memberof IndexModel
	 */
	public funcs: any[] = [
        {
            appfunctag: 'Auto22',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'pimpersonsetattrulesgridview',
            deResParameters: [],
            routepath: '/index/:index?/pimpeople/:pimperson?/setattrulesgridview/:setattrulesgridview?',
            parameters: [
                { pathName: 'pimpeople', parameterName: 'pimperson' },
                { pathName: 'setattrulesgridview', parameterName: 'setattrulesgridview' },
            ],
        },
        {
            appfunctag: 'Auto43',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'vacleavedetailgridview',
            deResParameters: [],
            routepath: '/index/:index?/vacleavedetails/:vacleavedetail?/gridview/:gridview?',
            parameters: [
                { pathName: 'vacleavedetails', parameterName: 'vacleavedetail' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto33',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'vacsynjcxgridview',
            deResParameters: [],
            routepath: '/index/:index?/vacsynjcxes/:vacsynjcx?/gridview/:gridview?',
            parameters: [
                { pathName: 'vacsynjcxes', parameterName: 'vacsynjcx' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto45',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'attendencesetupkqsztreeexpview',
            deResParameters: [],
            routepath: '/index/:index?/attendencesetups/:attendencesetup?/kqsztreeexpview/:kqsztreeexpview?',
            parameters: [
                { pathName: 'attendencesetups', parameterName: 'attendencesetup' },
                { pathName: 'kqsztreeexpview', parameterName: 'kqsztreeexpview' },
            ],
        },
        {
            appfunctag: 'Auto21',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'vacleacetypegridview',
            deResParameters: [],
            routepath: '/index/:index?/vacleacetypes/:vacleacetype?/gridview/:gridview?',
            parameters: [
                { pathName: 'vacleacetypes', parameterName: 'vacleacetype' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto26',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'attendancemreportkqybtreeexpview',
            deResParameters: [],
            routepath: '/index/:index?/attendancemreports/:attendancemreport?/kqybtreeexpview/:kqybtreeexpview?',
            parameters: [
                { pathName: 'attendancemreports', parameterName: 'attendancemreport' },
                { pathName: 'kqybtreeexpview', parameterName: 'kqybtreeexpview' },
            ],
        },
        {
            appfunctag: 'Auto35',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'attendancesettingsfygzzkqgridview',
            deResParameters: [],
            routepath: '/index/:index?/attendancesettings/:attendancesettings?/fygzzkqgridview/:fygzzkqgridview?',
            parameters: [
                { pathName: 'attendancesettings', parameterName: 'attendancesettings' },
                { pathName: 'fygzzkqgridview', parameterName: 'fygzzkqgridview' },
            ],
        },
        {
            appfunctag: 'Auto40',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'vacholidayrulesgridview',
            deResParameters: [],
            routepath: '/index/:index?/vacholidayrules/:vacholidayrules?/gridview/:gridview?',
            parameters: [
                { pathName: 'vacholidayrules', parameterName: 'vacholidayrules' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto42',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'attendencetypegridview',
            deResParameters: [],
            routepath: '/index/:index?/attendencetypes/:attendencetype?/gridview/:gridview?',
            parameters: [
                { pathName: 'attendencetypes', parameterName: 'attendencetype' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto27',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'attendancerecordgridview',
            deResParameters: [],
            routepath: '/index/:index?/attendancerecords/:attendancerecord?/gridview/:gridview?',
            parameters: [
                { pathName: 'attendancerecords', parameterName: 'attendancerecord' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto31',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'attensummarykqhztreeexpview',
            deResParameters: [],
            routepath: '/index/:index?/attensummaries/:attensummary?/kqhztreeexpview/:kqhztreeexpview?',
            parameters: [
                { pathName: 'attensummaries', parameterName: 'attensummary' },
                { pathName: 'kqhztreeexpview', parameterName: 'kqhztreeexpview' },
            ],
        },
	];

    /**
     * 获取所有菜单项集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppMenuItems(): any[] {
        return this.items;
    }

    /**
     * 获取所有应用功能集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppFuncs(): any[] {
        return this.funcs;
    }
}