server:
  port: 36093
#Log配置
logging:
  level:
    cn.ibizlab.ehr: info
#zuul网关路由设置
zuul:
  routes:
    pcmworkresume:
      path: /pcmworkresumes/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmprofileapproval:
      path: /pcmprofileapprovals/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmgxml:
      path: /pcmgxmls/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormorg:
      path: /ormorgs/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmpracticeexperience:
      path: /pcmpracticeexperiences/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormduty:
      path: /ormduties/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimcity:
      path: /pimcities/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmprofileinitnumber:
      path: /pcmprofileinitnumbers/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimstafftype:
      path: /pimstafftypes/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmprofileszyjtj:
      path: /pcmprofileszyjtjs/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmxkml:
      path: /pcmxkmls/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmprofileyjtjtemp:
      path: /pcmprofileyjtjtemps/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmprofilespyy:
      path: /pcmprofilespyys/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormqygl:
      path: /ormqygls/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmprofilefj:
      path: /pcmprofilefjs/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmzpmeglmx:
      path: /pcmzpmeglmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    codeitem:
      path: /codeitems/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmprofilenumbeprefix:
      path: /pcmprofilenumbeprefixes/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmcertofreg:
      path: /pcmcertofregs/**
      serviceId: ehr-webapi
      stripPrefix: false
    tdzwxx:
      path: /pcmtdzwxxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    codelist:
      path: /codelist1s/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormorgsector:
      path: /ormorgsectors/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmschooloffice:
      path: /pcmschooloffices/**
      serviceId: ehr-webapi
      stripPrefix: false
    testresult:
      path: /pcmtestresults/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmzpmegl:
      path: /pcmzpmegls/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmprofile:
      path: /pcmprofiles/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmawardswons:
      path: /pcmawardswons/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmeducationexperience:
      path: /pcmeducationexperiences/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormpost:
      path: /ormposts/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimqualmajor:
      path: /pimqualmajors/**
      serviceId: ehr-webapi
      stripPrefix: false
    wzd0001:
      path: /pcmwzd0001s/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimperson:
      path: /pimpeople/**
      serviceId: ehr-webapi
      stripPrefix: false
    pcmgxxktemp:
      path: /pcmgxxktemps/**
      serviceId: ehr-webapi
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
