/**
 * Index 部件模型
 *
 * @export
 * @class IndexModel
 */
export default class IndexModel {

    /**
     * 菜单项集合
     *
     * @public
     * @type {any[]}
     * @memberof IndexModel
     */
    public items: any[] = [
        {
	id: 'F7678570-4284-4B33-965C-03C544E3BCE6',
	name: 'menuitem1',
	text: '通知发布',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '通知发布',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/lianghuamubiaotianbao.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem1',
	items: [
		{
	id: 'FC6CD42F-45FF-4CB2-9850-5E8D9218B0D2',
	name: 'menuitem7',
	text: '通知发布',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '通知发布',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jlgl/1/xiangmugongzibiaozhun.png',
	textcls: '',
	appfunctag: 'Auto79',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem7',
},
	],
},
        {
	id: 'B79E0B4B-11A3-4C16-985A-7C55F7F490C7',
	name: 'menuitem2',
	text: '基础设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '基础设置',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jcgl/1/xiujiaxinxi.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem2',
	items: [
		{
	id: 'E19489FC-D484-4DE0-B218-6DCA4FF50339',
	name: 'menuitem6',
	text: '考核周期设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考核周期设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/kaoqinshezhi.png',
	textcls: '',
	appfunctag: 'Auto68',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem6',
},
		{
	id: '14E00FFD-6F8F-4ECC-9E87-75D9B3D1DE36',
	name: 'menuitem8',
	text: '考核对象设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考核对象设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jcgl/1/jiaoyuxinxi.png',
	textcls: '',
	appfunctag: 'Auto73',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem8',
},
		{
	id: '83F86EA3-C604-42D0-8B4C-0F1CD5DA39D7',
	name: 'menuitem9',
	text: '考核内容设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考核内容设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunziliao.png',
	textcls: '',
	appfunctag: 'Auto78',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem9',
},
		{
	id: '2478FB45-F88E-4229-B80C-CBF1DC306016',
	name: 'menuitem10',
	text: '评分权重设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '评分权重设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jcgl/1/fenpeixinxi.png',
	textcls: '',
	appfunctag: 'Auto75',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem10',
},
		{
	id: 'F80FBD50-7777-4C00-8E69-EC83A9366233',
	name: 'menuitem16',
	text: '积分规则设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '积分规则设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/lungangguize.png',
	textcls: '',
	appfunctag: 'Auto80',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem16',
},
	],
},
        {
	id: '44A4592F-0270-4059-A0C8-ACB1499AF5AE',
	name: 'menuitem12',
	text: '绩效标准',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '绩效标准',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jcgl/1/danganxinxi.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem12',
	items: [
		{
	id: '09B9B5BB-1EFB-49FF-B0E8-A4D55AD17D19',
	name: 'menuitem19',
	text: '考核模板设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考核模板设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/kaohexiangshezhi.png',
	textcls: '',
	appfunctag: '_2',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem19',
},
		{
	id: '62E103D7-2A91-4752-8A15-0C9D6AA9147E',
	name: 'menuitem11',
	text: '考核方案设置',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '考核方案设置',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/yuangongkaohefenleiyilanbiao.png',
	textcls: '',
	appfunctag: 'Auto63',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem11',
},
	],
},
        {
	id: 'E7E5CD4C-661D-4349-96C9-EBBA3F060DFE',
	name: 'menuitem3',
	text: '绩效考核',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '绩效考核',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/jixiaoguanli.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem3',
	items: [
		{
	id: 'DE9D9CDA-9535-43DB-865D-9DA75F060EC9',
	name: 'menuitem13',
	text: '年度量化目标填报',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '年度量化目标填报',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/lianghuamubiaotianbao.png',
	textcls: '',
	appfunctag: 'Auto70',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem13',
},
		{
	id: 'FC28EC7A-8FCF-457D-A59E-E65E8A35C2E1',
	name: 'menuitem14',
	text: '年度量化目标修正',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '年度量化目标修正',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/penxunxuqiu.png',
	textcls: '',
	appfunctag: 'Auto72',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem14',
},
		{
	id: '366710F6-48EF-4DB7-8A50-1CD519EAFCA7',
	name: 'menuitem15',
	text: '年度量化目标考核',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '年度量化目标考核',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/lianghuamubiaokaohe.png',
	textcls: '',
	appfunctag: 'Auto64',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem15',
},
	],
},
        {
	id: '2F60AB7A-CF33-494F-A31A-AC27911B89A8',
	name: 'menuitem4',
	text: '绩效定级',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '绩效定级',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/jixiaojieguo.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem4',
	items: [
		{
	id: 'BBA26F76-4C73-4069-B34C-036366DCF924',
	name: 'menuitem17',
	text: '绩效考核结果',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '绩效考核结果',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jxgl/1/jixiaokaohejieguofabu.png',
	textcls: '',
	appfunctag: 'Auto67',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem17',
},
		{
	id: '9256F357-16E5-4A4C-B90B-0BD82C0CE4A8',
	name: 'menuitem18',
	text: '绩效考核定级',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '绩效考核定级',
	expanded: false,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/jxgl/1/jixiaokaohepinggu.png',
	textcls: '',
	appfunctag: 'Auto50',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem18',
},
	],
},
        {
	id: '68BAE88C-A429-4EC7-BF6D-097AFDF05202',
	name: 'menuitem5',
	text: '绩效应用',
	type: 'MENUITEM',
	counterid: '',
	tooltip: '绩效应用',
	expanded: true,
	separator: false,
	hidden: false,
	hidesidebar: false,
	opendefault: false,
	iconcls: '',
	icon: '../../../img/newimage/1/jixiaoyingyong.png',
	textcls: '',
	appfunctag: '',
	resourcetag: '',
	authtag:'EHRPar-Index-menuitem5',
},
    ];

	/**
	 * 应用功能集合
	 *
	 * @public
	 * @type {any[]}
	 * @memberof IndexModel
	 */
	public funcs: any[] = [
        {
            appfunctag: 'Auto68',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parexamcyclenewgridview',
            deResParameters: [],
            routepath: '/index/:index?/parexamcycles/:parexamcycle?/newgridview/:newgridview?',
            parameters: [
                { pathName: 'parexamcycles', parameterName: 'parexamcycle' },
                { pathName: 'newgridview', parameterName: 'newgridview' },
            ],
        },
        {
            appfunctag: '_2',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parassesstemplategridview',
            deResParameters: [],
            routepath: '/index/:index?/parassesstemplates/:parassesstemplate?/gridview/:gridview?',
            parameters: [
                { pathName: 'parassesstemplates', parameterName: 'parassesstemplate' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto70',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parldndlhmbgridview',
            deResParameters: [],
            routepath: '/index/:index?/parldndlhmbs/:parldndlhmb?/gridview/:gridview?',
            parameters: [
                { pathName: 'parldndlhmbs', parameterName: 'parldndlhmb' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto78',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parexamcontentgridview',
            deResParameters: [],
            routepath: '/index/:index?/parexamcontents/:parexamcontent?/gridview/:gridview?',
            parameters: [
                { pathName: 'parexamcontents', parameterName: 'parexamcontent' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto79',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'partzgggridview',
            deResParameters: [],
            routepath: '/index/:index?/partzggs/:partzgg?/gridview/:gridview?',
            parameters: [
                { pathName: 'partzggs', parameterName: 'partzgg' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto50',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parjxjgjxpgdjgridview',
            deResParameters: [],
            routepath: '/index/:index?/parjxjgs/:parjxjg?/jxpgdjgridview/:jxpgdjgridview?',
            parameters: [
                { pathName: 'parjxjgs', parameterName: 'parjxjg' },
                { pathName: 'jxpgdjgridview', parameterName: 'jxpgdjgridview' },
            ],
        },
        {
            appfunctag: 'Auto72',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parldndlhmbndlhmbxzgridview',
            deResParameters: [],
            routepath: '/index/:index?/parldndlhmbs/:parldndlhmb?/ndlhmbxzgridview/:ndlhmbxzgridview?',
            parameters: [
                { pathName: 'parldndlhmbs', parameterName: 'parldndlhmb' },
                { pathName: 'ndlhmbxzgridview', parameterName: 'ndlhmbxzgridview' },
            ],
        },
        {
            appfunctag: 'Auto64',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parldndlhmbkhgridview',
            deResParameters: [],
            routepath: '/index/:index?/parldndlhmbs/:parldndlhmb?/khgridview/:khgridview?',
            parameters: [
                { pathName: 'parldndlhmbs', parameterName: 'parldndlhmb' },
                { pathName: 'khgridview', parameterName: 'khgridview' },
            ],
        },
        {
            appfunctag: 'Auto80',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parintegralrulegridview',
            deResParameters: [],
            routepath: '/index/:index?/parintegralrules/:parintegralrule?/gridview/:gridview?',
            parameters: [
                { pathName: 'parintegralrules', parameterName: 'parintegralrule' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto73',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parkhfagridview',
            deResParameters: [],
            routepath: '/index/:index?/parkhfas/:parkhfa?/gridview/:gridview?',
            parameters: [
                { pathName: 'parkhfas', parameterName: 'parkhfa' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto67',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parjxjggridview',
            deResParameters: [],
            routepath: '/index/:index?/parjxjgs/:parjxjg?/gridview/:gridview?',
            parameters: [
                { pathName: 'parjxjgs', parameterName: 'parjxjg' },
                { pathName: 'gridview', parameterName: 'gridview' },
            ],
        },
        {
            appfunctag: 'Auto63',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parjxkhxhzygkhxgridview',
            deResParameters: [],
            routepath: '/index/:index?/parjxkhxhzs/:parjxkhxhz?/ygkhxgridview/:ygkhxgridview?',
            parameters: [
                { pathName: 'parjxkhxhzs', parameterName: 'parjxkhxhz' },
                { pathName: 'ygkhxgridview', parameterName: 'ygkhxgridview' },
            ],
        },
        {
            appfunctag: 'Auto75',
            appfuncyype: 'APPVIEW',
            openmode: '',
            codename: 'parldkhqznewgridview',
            deResParameters: [],
            routepath: '/index/:index?/parldkhqzs/:parldkhqz?/newgridview/:newgridview?',
            parameters: [
                { pathName: 'parldkhqzs', parameterName: 'parldkhqz' },
                { pathName: 'newgridview', parameterName: 'newgridview' },
            ],
        },
	];

    /**
     * 获取所有菜单项集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppMenuItems(): any[] {
        return this.items;
    }

    /**
     * 获取所有应用功能集合
     *
     * @returns {any[]}
     * @memberof IndexModel
     */
    public getAppFuncs(): any[] {
        return this.funcs;
    }
}