server:
  port: 36095
#Log配置
logging:
  level:
    cn.ibizlab.ehr: info
#zuul网关路由设置
zuul:
  routes:
    attendencetype:
      path: /attendencetypes/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacleavedetail:
      path: /vacleavedetails/**
      serviceId: ehr-webapi
      stripPrefix: false
    personstatemgr:
      path: /personstatemgrs/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacleavetips:
      path: /vacleavetips/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormorg:
      path: /ormorgs/**
      serviceId: ehr-webapi
      stripPrefix: false
    attendancemreport:
      path: /attendancemreports/**
      serviceId: ehr-webapi
      stripPrefix: false
    pimperson:
      path: /pimpeople/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacholidayrules:
      path: /vacholidayrules/**
      serviceId: ehr-webapi
      stripPrefix: false
    attendenceormorgsector:
      path: /attendenceormorgscetors/**
      serviceId: ehr-webapi
      stripPrefix: false
    attensummary:
      path: /attensummaries/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacsynjcx:
      path: /vacsynjcxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormorgsector:
      path: /ormorgsectors/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacholiday:
      path: /vacholidays/**
      serviceId: ehr-webapi
      stripPrefix: false
    attendencesetup:
      path: /attendencesetups/**
      serviceId: ehr-webapi
      stripPrefix: false
    attendancesettings:
      path: /attendancesettings/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormbmkqdz:
      path: /ormbmkqdzs/**
      serviceId: ehr-webapi
      stripPrefix: false
    attendancemreportmx:
      path: /attendancemreportmxes/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacleacetype:
      path: /vacleacetypes/**
      serviceId: ehr-webapi
      stripPrefix: false
    vacleavemanage:
      path: /vacleavemanages/**
      serviceId: ehr-webapi
      stripPrefix: false
    attendancerecord:
      path: /attendancerecords/**
      serviceId: ehr-webapi
      stripPrefix: false
    wzd0001:
      path: /pcmwzd0001s/**
      serviceId: ehr-webapi
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
