package cn.ibizlab.ehr.common.logic.orguserlogic.updaterelatedinfo;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.common.domain.OrgUser orguserupdaterelatedinfodefault;
global cn.ibizlab.ehr.core.common.domain.User orguserupdaterelatedinfouser;
global cn.ibizlab.ehr.core.common.service.IUserService userservice;
global cn.ibizlab.ehr.core.common.service.IOrgUserService iBzSysOrguserDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "orguserupdaterelatedinfobegin"
    when
    then
    end

//逻辑处理节点[准备用户对象参数]
rule "prepareparam1"
ruleflow-group "orguserupdaterelatedinfoprepareparam1"
    when
    then
    orguserupdaterelatedinfouser.set("userid",orguserupdaterelatedinfodefault.get("orguserid"));
    orguserupdaterelatedinfouser.set("username",orguserupdaterelatedinfodefault.get("orgusername"));
    orguserupdaterelatedinfouser.set("validflag",orguserupdaterelatedinfodefault.get("validflag"));
    update(orguserupdaterelatedinfodefault);//更新fact中变量值
    update(orguserupdaterelatedinfouser);//更新fact中变量值
    end

//逻辑处理节点[保存用户]
rule "deaction1"
ruleflow-group "orguserupdaterelatedinfodeaction1"
    when
    then
    userservice.save(orguserupdaterelatedinfouser);
    update(orguserupdaterelatedinfodefault);//更新fact中变量值
    update(orguserupdaterelatedinfouser);//更新fact中变量值
    end

