package cn.ibizlab.ehr.common.logic.orguserlogic.createrelatedinfo;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.common.domain.User orgusercreaterelatedinfouser;
global cn.ibizlab.ehr.core.common.domain.UserDict orgusercreaterelatedinfouserdict;
global cn.ibizlab.ehr.core.common.domain.OrgUser orgusercreaterelatedinfodefault;
global cn.ibizlab.ehr.core.common.service.IUserService userservice;
global cn.ibizlab.ehr.core.common.service.IUserDictService userdictservice;
global cn.ibizlab.ehr.core.common.service.IOrgUserService iBzSysOrguserDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[保存用户]
rule "deaction1"
ruleflow-group "orgusercreaterelatedinfodeaction1"
    when
    then
    userservice.create(orgusercreaterelatedinfouser);
    update(orgusercreaterelatedinfouser);//更新fact中变量值
    update(orgusercreaterelatedinfouserdict);//更新fact中变量值
    update(orgusercreaterelatedinfodefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "orgusercreaterelatedinfobegin"
    when
    then
    end

//逻辑处理节点[准备用户对象参数]
rule "prepareparam1"
ruleflow-group "orgusercreaterelatedinfoprepareparam1"
    when
    then
    orgusercreaterelatedinfouser.set("userid",orgusercreaterelatedinfodefault.get("orguserid"));
    orgusercreaterelatedinfouser.set("username",orgusercreaterelatedinfodefault.get("orgusername"));
    update(orgusercreaterelatedinfouser);//更新fact中变量值
    update(orgusercreaterelatedinfouserdict);//更新fact中变量值
    update(orgusercreaterelatedinfodefault);//更新fact中变量值
    end

//逻辑处理节点[建立用户词典]
rule "deaction2"
ruleflow-group "orgusercreaterelatedinfodeaction2"
    when
    then
    userdictservice.create(orgusercreaterelatedinfouserdict);
    update(orgusercreaterelatedinfouser);//更新fact中变量值
    update(orgusercreaterelatedinfouserdict);//更新fact中变量值
    update(orgusercreaterelatedinfodefault);//更新fact中变量值
    end

//逻辑处理节点[准备用户词典数据对象]
rule "prepareparam2"
ruleflow-group "orgusercreaterelatedinfoprepareparam2"
    when
    then
    orgusercreaterelatedinfouserdict.set("ownerid",orgusercreaterelatedinfodefault.get("orguserid"));
    orgusercreaterelatedinfouserdict.set("userdictid",orgusercreaterelatedinfodefault.get("orguserid"));
    orgusercreaterelatedinfouserdict.set("userdictname",orgusercreaterelatedinfodefault.get("orgusername"));
    orgusercreaterelatedinfouserdict.set("ownertype","ORGUSER");
    update(orgusercreaterelatedinfouser);//更新fact中变量值
    update(orgusercreaterelatedinfouserdict);//更新fact中变量值
    update(orgusercreaterelatedinfodefault);//更新fact中变量值
    end

