package cn.ibizlab.ehr.common.logic.orguserlogic.updatecuruser;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.common.domain.OrgUser orguserupdatecuruserdefault;
global cn.ibizlab.ehr.core.common.service.IOrgUserService orguserservice;
global cn.ibizlab.ehr.core.common.service.IOrgUserService iBzSysOrguserDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[更新]
rule "deaction1"
ruleflow-group "orguserupdatecuruserdeaction1"
    when
    then
    orguserservice.update(orguserupdatecuruserdefault);
    update(orguserupdatecuruserdefault);//更新fact中变量值
    end

//逻辑处理节点[修改当前用户标示]
rule "prepareparam1"
ruleflow-group "orguserupdatecuruserprepareparam1"
    when
    then
    orguserupdatecuruserdefault.set("orguserid",curuser.getSessionParams().get("srfpersonid"));
    update(orguserupdatecuruserdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "orguserupdatecuruserbegin"
    when
    then
    end

