package cn.ibizlab.ehr.common.logic.orguserlogic.getcuruser;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.common.domain.OrgUser orgusergetcuruserdefault;
global cn.ibizlab.ehr.core.common.service.IOrgUserService orguserservice;
global cn.ibizlab.ehr.core.common.service.IOrgUserService iBzSysOrguserDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[修改当前用户标示]
rule "prepareparam1"
ruleflow-group "orgusergetcuruserprepareparam1"
    when
    then
    orgusergetcuruserdefault.set("orguserid",curuser.getSessionParams().get("srfpersonid"));
    update(orgusergetcuruserdefault);//更新fact中变量值
    end

//逻辑处理节点[获取]
rule "deaction1"
ruleflow-group "orgusergetcuruserdeaction1"
    when
    then
    cn.ibizlab.ehr.util.helper.CachedBeanCopier.copy(orguserservice.get(orgusergetcuruserdefault.getOrguserid()),orgusergetcuruserdefault);
    update(orgusergetcuruserdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "orgusergetcuruserbegin"
    when
    then
    end

