package cn.ibizlab.ehr.orm.logic.ormuserlogic.createrelatedinfo;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.orm.domain.ORMUSER ormusercreaterelatedinfodefault;
global cn.ibizlab.ehr.core.common.domain.UserDict ormusercreaterelatedinfouserdict;
global cn.ibizlab.ehr.core.common.domain.User ormusercreaterelatedinfouser;
global cn.ibizlab.ehr.core.common.service.IUserDictService userdictservice;
global cn.ibizlab.ehr.core.common.service.IUserService userservice;
global cn.ibizlab.ehr.core.orm.service.IORMUSERService iBzSysOrmuserDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ormusercreaterelatedinfobegin"
    when
    then
    end

//逻辑处理节点[准备用户词典数据对象]
rule "prepareparam2"
ruleflow-group "ormusercreaterelatedinfoprepareparam2"
    when
    then
    ormusercreaterelatedinfouserdict.set("ownerid",ormusercreaterelatedinfodefault.get("orguserid"));
    ormusercreaterelatedinfouserdict.set("userdictid",ormusercreaterelatedinfodefault.get("orguserid"));
    ormusercreaterelatedinfouserdict.set("userdictname",ormusercreaterelatedinfodefault.get("orgusername"));
    ormusercreaterelatedinfouserdict.set("ownertype","ORGUSER");
    update(ormusercreaterelatedinfodefault);//更新fact中变量值
    update(ormusercreaterelatedinfouserdict);//更新fact中变量值
    update(ormusercreaterelatedinfouser);//更新fact中变量值
    end

//逻辑处理节点[建立用户词典]
rule "deaction2"
ruleflow-group "ormusercreaterelatedinfodeaction2"
    when
    then
    userdictservice.create(ormusercreaterelatedinfouserdict);
    update(ormusercreaterelatedinfodefault);//更新fact中变量值
    update(ormusercreaterelatedinfouserdict);//更新fact中变量值
    update(ormusercreaterelatedinfouser);//更新fact中变量值
    end

//逻辑处理节点[保存用户]
rule "deaction1"
ruleflow-group "ormusercreaterelatedinfodeaction1"
    when
    then
    userservice.create(ormusercreaterelatedinfouser);
    update(ormusercreaterelatedinfodefault);//更新fact中变量值
    update(ormusercreaterelatedinfouserdict);//更新fact中变量值
    update(ormusercreaterelatedinfouser);//更新fact中变量值
    end

//逻辑处理节点[准备用户对象参数]
rule "prepareparam1"
ruleflow-group "ormusercreaterelatedinfoprepareparam1"
    when
    then
    ormusercreaterelatedinfouser.set("userid",ormusercreaterelatedinfodefault.get("orguserid"));
    ormusercreaterelatedinfouser.set("username",ormusercreaterelatedinfodefault.get("orgusername"));
    update(ormusercreaterelatedinfodefault);//更新fact中变量值
    update(ormusercreaterelatedinfouserdict);//更新fact中变量值
    update(ormusercreaterelatedinfouser);//更新fact中变量值
    end

