package cn.ibizlab.ehr.orm.logic.ormuserlogic.updaterelatedinfo;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.common.domain.User ormuserupdaterelatedinfouser;
global cn.ibizlab.ehr.core.orm.domain.ORMUSER ormuserupdaterelatedinfodefault;
global cn.ibizlab.ehr.core.common.service.IUserService userservice;
global cn.ibizlab.ehr.core.orm.service.IORMUSERService iBzSysOrmuserDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[准备用户对象参数]
rule "prepareparam1"
ruleflow-group "ormuserupdaterelatedinfoprepareparam1"
    when
    then
    ormuserupdaterelatedinfouser.set("userid",ormuserupdaterelatedinfodefault.get("orguserid"));
    ormuserupdaterelatedinfouser.set("validflag",ormuserupdaterelatedinfodefault.get("validflag"));
    ormuserupdaterelatedinfouser.set("username",ormuserupdaterelatedinfodefault.get("orgusername"));
    update(ormuserupdaterelatedinfouser);//更新fact中变量值
    update(ormuserupdaterelatedinfodefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "ormuserupdaterelatedinfobegin"
    when
    then
    end

//逻辑处理节点[保存用户]
rule "deaction1"
ruleflow-group "ormuserupdaterelatedinfodeaction1"
    when
    then
    userservice.save(ormuserupdaterelatedinfouser);
    update(ormuserupdaterelatedinfouser);//更新fact中变量值
    update(ormuserupdaterelatedinfodefault);//更新fact中变量值
    end

