package cn.ibizlab.ehr.pcm.logic.pcmbdsqdmxlogic.zjjscodelist3;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmBdsqdmx pcmbdsqdmxzjjscodelist3default;
global cn.ibizlab.ehr.core.common.domain.CodeList1 pcmbdsqdmxzjjscodelist3zjcodelist;
global cn.ibizlab.ehr.core.common.service.ICodeList1Service codelist1service;
global cn.ibizlab.ehr.core.pcm.service.IPcmBdsqdmxService iBzSysPcmbdsqdmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmbdsqdmxzjjscodelist3begin"
    when
    then
    end

//逻辑处理节点[zjcodelist]
rule "prepareparam1"
ruleflow-group "pcmbdsqdmxzjjscodelist3prepareparam1"
    when
    then
    pcmbdsqdmxzjjscodelist3zjcodelist.set("codelistid","BC61C8E1-837D-4711-9E49-3061DBBFAFEA");
    update(pcmbdsqdmxzjjscodelist3default);//更新fact中变量值
    update(pcmbdsqdmxzjjscodelist3zjcodelist);//更新fact中变量值
    end

//逻辑处理节点[刷新代码表]
rule "deaction1"
ruleflow-group "pcmbdsqdmxzjjscodelist3deaction1"
    when
    then
    codelist1service.refreshModel(pcmbdsqdmxzjjscodelist3zjcodelist);
    update(pcmbdsqdmxzjjscodelist3default);//更新fact中变量值
    update(pcmbdsqdmxzjjscodelist3zjcodelist);//更新fact中变量值
    end

