package cn.ibizlab.ehr.pcm.logic.pcmbdsqdmxlogic.setsj;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PCMBDSQDMX pcmbdsqdmxsetsjdefault;
global cn.ibizlab.ehr.core.pcm.service.IPCMBDSQDMXService iBzSysPcmbdsqdmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置其他的时间为生效日期]
rule "prepareparam1"
ruleflow-group "pcmbdsqdmxsetsjprepareparam1"
    when
    then
    pcmbdsqdmxsetsjdefault.set("gzkssj",pcmbdsqdmxsetsjdefault.get("sxrq"));
    pcmbdsqdmxsetsjdefault.set("lzsj",pcmbdsqdmxsetsjdefault.get("sxrq"));
    update(pcmbdsqdmxsetsjdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmbdsqdmxsetsjbegin"
    when
    then
    end

