package cn.ibizlab.ehr.pcm.logic.pcmddsqdmxlogic.setsj;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PCMDDSQDMX pcmddsqdmxsetsjdefault;
global cn.ibizlab.ehr.core.pcm.service.IPCMDDSQDMXService iBzSysPcmddsqdmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置其他时间]
rule "prepareparam1"
ruleflow-group "pcmddsqdmxsetsjprepareparam1"
    when
    then
    pcmddsqdmxsetsjdefault.set("jdkssj",pcmddsqdmxsetsjdefault.get("sxrq"));
    update(pcmddsqdmxsetsjdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmddsqdmxsetsjbegin"
    when
    then
    end

