package cn.ibizlab.ehr.pcm.logic.pcmddsqdmxlogic.setsxrq;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PCMDDSQDMX pcmddsqdmxsetsxrqdefault;
global cn.ibizlab.ehr.core.pcm.service.IPCMDDSQDMXService iBzSysPcmddsqdmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmddsqdmxsetsxrqbegin"
    when
    then
    end

//逻辑处理节点[设置生效日期]
rule "prepareparam1"
ruleflow-group "pcmddsqdmxsetsxrqprepareparam1"
    when
    then
    pcmddsqdmxsetsxrqdefault.set("sxrq",pcmddsqdmxsetsxrqdefault.get("jdkssj"));
    update(pcmddsqdmxsetsxrqdefault);//更新fact中变量值
    end

