package cn.ibizlab.ehr.pcm.logic.pcmjxsygzzjlmxlogic.setreject;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmJxsygzzjlmx pcmjxsygzzjlmxsetrejectdefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmJxsygzzjlmxService iBzSysPcmjxsygzzjlmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置准备参数]
rule "prepareparam1"
ruleflow-group "pcmjxsygzzjlmxsetrejectprepareparam1"
    when
    then
    pcmjxsygzzjlmxsetrejectdefault.set("finished","1");
    pcmjxsygzzjlmxsetrejectdefault.set("checkstatus","4");
    update(pcmjxsygzzjlmxsetrejectdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmjxsygzzjlmxsetrejectbegin"
    when
    then
    end

