package cn.ibizlab.ehr.pcm.logic.pcmprofilelogic.forward;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmProfile pcmprofileforwarddefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService pcmprofileservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService iBzSysPcmprofileDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[变更状态为待总部初审]
rule "deaction1"
ruleflow-group "pcmprofileforwarddeaction1"
    when
    then
    pcmprofileservice.update(pcmprofileforwarddefault);
    update(pcmprofileforwarddefault);//更新fact中变量值
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "pcmprofileforwardprepareparam1"
    when
    then
    pcmprofileforwarddefault.set("profiletype","30");
    update(pcmprofileforwarddefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmprofileforwardbegin"
    when
    then
    end

