package cn.ibizlab.ehr.pcm.logic.pcmprofilelogic.checkin;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmProfile pcmprofilecheckindefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService pcmprofileservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService iBzSysPcmprofileDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "pcmprofilecheckinprepareparam1"
    when
    then
    pcmprofilecheckindefault.set("profiletype","70");
    update(pcmprofilecheckindefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmprofilecheckinbegin"
    when
    then
    end

//逻辑处理节点[变更状态为已报到]
rule "deaction1"
ruleflow-group "pcmprofilecheckindeaction1"
    when
    then
    pcmprofileservice.update(pcmprofilecheckindefault);
    update(pcmprofilecheckindefault);//更新fact中变量值
    end

