package cn.ibizlab.ehr.pcm.logic.pcmprofilelogic.submit;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmProfile pcmprofilesubmitdefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService pcmprofileservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService iBzSysPcmprofileDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "pcmprofilesubmitprepareparam1"
    when
    then
    pcmprofilesubmitdefault.set("profiletype","15");
    update(pcmprofilesubmitdefault);//更新fact中变量值
    end

//逻辑处理节点[变更状态为待公司初审]
rule "deaction1"
ruleflow-group "pcmprofilesubmitdeaction1"
    when
    then
    pcmprofileservice.update(pcmprofilesubmitdefault);
    update(pcmprofilesubmitdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmprofilesubmitbegin"
    when
    then
    end

