package cn.ibizlab.ehr.pcm.logic.pcmprofilelogic.precheckin;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmProfile pcmprofileprecheckindefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService pcmprofileservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService iBzSysPcmprofileDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[变更状态为待报到]
rule "deaction1"
ruleflow-group "pcmprofileprecheckindeaction1"
    when
    then
    pcmprofileservice.update(pcmprofileprecheckindefault);
    update(pcmprofileprecheckindefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmprofileprecheckinbegin"
    when
    then
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "pcmprofileprecheckinprepareparam1"
    when
    then
    pcmprofileprecheckindefault.set("profiletype","65");
    update(pcmprofileprecheckindefault);//更新fact中变量值
    end

