package cn.ibizlab.ehr.pcm.logic.pcmprofilelogic.companyreject;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmProfile pcmprofilecompanyrejectdefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService pcmprofileservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService iBzSysPcmprofileDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmprofilecompanyrejectbegin"
    when
    then
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "pcmprofilecompanyrejectprepareparam1"
    when
    then
    pcmprofilecompanyrejectdefault.set("profiletype","20");
    update(pcmprofilecompanyrejectdefault);//更新fact中变量值
    end

//逻辑处理节点[变更状态为公司审批不通过]
rule "deaction1"
ruleflow-group "pcmprofilecompanyrejectdeaction1"
    when
    then
    pcmprofileservice.update(pcmprofilecompanyrejectdefault);
    update(pcmprofilecompanyrejectdefault);//更新fact中变量值
    end

