package cn.ibizlab.ehr.pcm.logic.pcmprofilelogic.groupreject;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmProfile pcmprofilegrouprejectdefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService pcmprofileservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmProfileService iBzSysPcmprofileDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmprofilegrouprejectbegin"
    when
    then
    end

//逻辑处理节点[变更状态为总部审批不通过]
rule "deaction1"
ruleflow-group "pcmprofilegrouprejectdeaction1"
    when
    then
    pcmprofileservice.update(pcmprofilegrouprejectdefault);
    update(pcmprofilegrouprejectdefault);//更新fact中变量值
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "pcmprofilegrouprejectprepareparam1"
    when
    then
    pcmprofilegrouprejectdefault.set("profiletype","50");
    update(pcmprofilegrouprejectdefault);//更新fact中变量值
    end

