package cn.ibizlab.ehr.pcm.logic.pcmtxfpsqlogic.fillpersoninfo;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmTxfpsq pcmtxfpsqfillpersoninfodefault;
global cn.ibizlab.ehr.core.pim.domain.PimPerson pcmtxfpsqfillpersoninfopimperson;
global cn.ibizlab.ehr.core.pim.service.IPimPersonService pimpersonservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmTxfpsqService iBzSysPcmtxfpsqDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置人员id]
rule "prepareparam1"
ruleflow-group "pcmtxfpsqfillpersoninfoprepareparam1"
    when
    then
    pcmtxfpsqfillpersoninfopimperson.set("pimpersonid",pcmtxfpsqfillpersoninfodefault.get("pimpersonid"));
    update(pcmtxfpsqfillpersoninfodefault);//更新fact中变量值
    update(pcmtxfpsqfillpersoninfopimperson);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmtxfpsqfillpersoninfobegin"
    when
    then
    end

//逻辑处理节点[查询人员信息]
rule "deaction1"
ruleflow-group "pcmtxfpsqfillpersoninfodeaction1"
    when
    then
    cn.ibizlab.ehr.util.helper.CachedBeanCopier.copy(pimpersonservice.get(pcmtxfpsqfillpersoninfopimperson.getPimpersonid()),pcmtxfpsqfillpersoninfopimperson);
    update(pcmtxfpsqfillpersoninfodefault);//更新fact中变量值
    update(pcmtxfpsqfillpersoninfopimperson);//更新fact中变量值
    end

//逻辑处理节点[填充用户信息]
rule "prepareparam2"
ruleflow-group "pcmtxfpsqfillpersoninfoprepareparam2"
    when
    then
    pcmtxfpsqfillpersoninfodefault.set("ygw",pcmtxfpsqfillpersoninfopimperson.get("gw"));
    pcmtxfpsqfillpersoninfodefault.set("ygbh",pcmtxfpsqfillpersoninfopimperson.get("ygbh"));
    pcmtxfpsqfillpersoninfodefault.set("yzw",pcmtxfpsqfillpersoninfopimperson.get("zw"));
    pcmtxfpsqfillpersoninfodefault.set("zzid",pcmtxfpsqfillpersoninfopimperson.get("ormorgid"));
    pcmtxfpsqfillpersoninfodefault.set("zz",pcmtxfpsqfillpersoninfopimperson.get("ormorgname"));
    pcmtxfpsqfillpersoninfodefault.set("bmid",pcmtxfpsqfillpersoninfopimperson.get("ormorgsectorid"));
    pcmtxfpsqfillpersoninfodefault.set("bm",pcmtxfpsqfillpersoninfopimperson.get("ormorgsectorname"));
    pcmtxfpsqfillpersoninfodefault.set("lxdh",pcmtxfpsqfillpersoninfopimperson.get("lxdh"));
    pcmtxfpsqfillpersoninfodefault.set("postaladdress",pcmtxfpsqfillpersoninfopimperson.get("postaladdress"));
    pcmtxfpsqfillpersoninfodefault.set("rank",pcmtxfpsqfillpersoninfopimperson.get("rank"));
    pcmtxfpsqfillpersoninfodefault.set("nl",pcmtxfpsqfillpersoninfopimperson.get("sfznl"));
    pcmtxfpsqfillpersoninfodefault.set("txdq",pcmtxfpsqfillpersoninfopimperson.get("sjtxrq"));
    update(pcmtxfpsqfillpersoninfodefault);//更新fact中变量值
    update(pcmtxfpsqfillpersoninfopimperson);//更新fact中变量值
    end

