package cn.ibizlab.ehr.pcm.logic.pcmxygzzjlmxlogic.setpass;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmXygzzjlmx pcmxygzzjlmxsetpassdefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmXygzzjlmxService iBzSysPcmxygzzjlmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmxygzzjlmxsetpassbegin"
    when
    then
    end

//逻辑处理节点[设置准备参数]
rule "prepareparam1"
ruleflow-group "pcmxygzzjlmxsetpassprepareparam1"
    when
    then
    pcmxygzzjlmxsetpassdefault.set("finished","1");
    pcmxygzzjlmxsetpassdefault.set("checkstatus","3");
    update(pcmxygzzjlmxsetpassdefault);//更新fact中变量值
    end

