package cn.ibizlab.ehr.pcm.logic.pcmydjpmxlogic.setfinished;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmYdjpmx pcmydjpmxsetfinisheddefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmYdjpmxService iBzSysPcmydjpmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置准备参数]
rule "prepareparam1"
ruleflow-group "pcmydjpmxsetfinishedprepareparam1"
    when
    then
    pcmydjpmxsetfinisheddefault.set("isfinished","1");
    update(pcmydjpmxsetfinisheddefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmydjpmxsetfinishedbegin"
    when
    then
    end

