package cn.ibizlab.ehr.pcm.logic.pcmydjdmxlogic.setcheckstatus;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmYdjdmx pcmydjdmxsetcheckstatusdefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmYdjdmxService iBzSysPcmydjdmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmydjdmxsetcheckstatusbegin"
    when
    then
    end

