package cn.ibizlab.ehr.pcm.logic.pcmydlzmxlogic.setfinished;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmYdlzmx pcmydlzmxsetfinisheddefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmYdlzmxService iBzSysPcmydlzmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置完成状态]
rule "prepareparam1"
ruleflow-group "pcmydlzmxsetfinishedprepareparam1"
    when
    then
    pcmydlzmxsetfinisheddefault.set("isfinished","1");
    update(pcmydlzmxsetfinisheddefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmydlzmxsetfinishedbegin"
    when
    then
    end

