package cn.ibizlab.ehr.pcm.logic.pcmyddgmxlogic.setfinished;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmYddgmx pcmyddgmxsetfinisheddefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmYddgmxService iBzSysPcmyddgmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置参数准备]
rule "prepareparam1"
ruleflow-group "pcmyddgmxsetfinishedprepareparam1"
    when
    then
    pcmyddgmxsetfinisheddefault.set("isfinished","1");
    update(pcmyddgmxsetfinisheddefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmyddgmxsetfinishedbegin"
    when
    then
    end

