package cn.ibizlab.ehr.pcm.logic.pcmydjdmxlogic.ryhg;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmYdjdmx pcmydjdmxryhgdefault;
global cn.ibizlab.ehr.core.pim.domain.PimDistirbution pcmydjdmxryhgpimdistirbution;
global cn.ibizlab.ehr.core.pim.service.IPimDistirbutionService pimdistirbutionservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmYdjdmxService iBzSysPcmydjdmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[更新分配表]
rule "prepareparam2"
ruleflow-group "pcmydjdmxryhgprepareparam2"
    when
    then
    pcmydjdmxryhgpimdistirbution.set("pimdistirbutionid",pcmydjdmxryhgdefault.get("pimdistirbutionid"));
    pcmydjdmxryhgpimdistirbution.set("fpzt","ZZFP");
    update(pcmydjdmxryhgdefault);//更新fact中变量值
    update(pcmydjdmxryhgpimdistirbution);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmydjdmxryhgbegin"
    when
    then
    end

//逻辑处理节点[更新分配表]
rule "deaction2"
ruleflow-group "pcmydjdmxryhgdeaction2"
    when
    then
    pimdistirbutionservice.update(pcmydjdmxryhgpimdistirbution);
    update(pcmydjdmxryhgdefault);//更新fact中变量值
    update(pcmydjdmxryhgpimdistirbution);//更新fact中变量值
    end

