package cn.ibizlab.ehr.pcm.logic.pcmydjzmxlogic.ryhg;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PimDistirbution pcmydjzmxryhgpimdistirbution;
global cn.ibizlab.ehr.core.pcm.domain.PcmYdjzmx pcmydjzmxryhgdefault;
global cn.ibizlab.ehr.core.pim.service.IPimDistirbutionService pimdistirbutionservice;
global cn.ibizlab.ehr.core.pcm.service.IPcmYdjzmxService iBzSysPcmydjzmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置参数准备]
rule "prepareparam1"
ruleflow-group "pcmydjzmxryhgprepareparam1"
    when
    then
    pcmydjzmxryhgpimdistirbution.set("pimdistirbutionid",pcmydjzmxryhgdefault.get("pimdistirbutionid"));
    pcmydjzmxryhgpimdistirbution.set("fpzt","ZZFP");
    update(pcmydjzmxryhgpimdistirbution);//更新fact中变量值
    update(pcmydjzmxryhgdefault);//更新fact中变量值
    end

//逻辑处理节点[更新分配表]
rule "deaction1"
ruleflow-group "pcmydjzmxryhgdeaction1"
    when
    then
    pimdistirbutionservice.update(pcmydjzmxryhgpimdistirbution);
    update(pcmydjzmxryhgpimdistirbution);//更新fact中变量值
    update(pcmydjzmxryhgdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmydjzmxryhgbegin"
    when
    then
    end

