package cn.ibizlab.ehr.pcm.logic.pcmydjzmxlogic.setfinished;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmYdjzmx pcmydjzmxsetfinisheddefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmYdjzmxService iBzSysPcmydjzmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置参数准备]
rule "prepareparam1"
ruleflow-group "pcmydjzmxsetfinishedprepareparam1"
    when
    then
    pcmydjzmxsetfinisheddefault.set("isfinished","1");
    update(pcmydjzmxsetfinisheddefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmydjzmxsetfinishedbegin"
    when
    then
    end

