package cn.ibizlab.ehr.pcm.logic.pcmydntmxlogic.setfinished;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pcm.domain.PcmYdntmx pcmydntmxsetfinisheddefault;
global cn.ibizlab.ehr.core.pcm.service.IPcmYdntmxService iBzSysPcmydntmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置参数准备]
rule "prepareparam1"
ruleflow-group "pcmydntmxsetfinishedprepareparam1"
    when
    then
    pcmydntmxsetfinisheddefault.set("isfinished","1");
    update(pcmydntmxsetfinisheddefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pcmydntmxsetfinishedbegin"
    when
    then
    end

