package cn.ibizlab.ehr.pim.logic.pimarchiveslogic.getpersonorg;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PimArchives pimarchivesgetpersonorgdefault;
global cn.ibizlab.ehr.core.pim.domain.PimPerson pimarchivesgetpersonorggerpersoninfo;
global cn.ibizlab.ehr.core.pim.service.IPimPersonService pimpersonservice;
global cn.ibizlab.ehr.core.pim.service.IPimArchivesService iBzSysPimarchivesDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[填充人员中的组织]
rule "prepareparam1"
ruleflow-group "pimarchivesgetpersonorgprepareparam1"
    when
    then
    pimarchivesgetpersonorgdefault.set("ormorgid",pimarchivesgetpersonorggerpersoninfo.get("ormorgid"));
    pimarchivesgetpersonorgdefault.set("ormorgname",pimarchivesgetpersonorggerpersoninfo.get("ormorgname"));
    update(pimarchivesgetpersonorgdefault);//更新fact中变量值
    update(pimarchivesgetpersonorggerpersoninfo);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimarchivesgetpersonorgbegin"
    when
    then
    end

//逻辑处理节点[获取人员信息]
rule "deaction1"
ruleflow-group "pimarchivesgetpersonorgdeaction1"
    when
    then
    cn.ibizlab.ehr.util.helper.CachedBeanCopier.copy(pimpersonservice.get(pimarchivesgetpersonorggerpersoninfo.getPimpersonid()),pimarchivesgetpersonorggerpersoninfo);
    update(pimarchivesgetpersonorgdefault);//更新fact中变量值
    update(pimarchivesgetpersonorggerpersoninfo);//更新fact中变量值
    end

