package cn.ibizlab.ehr.pim.logic.pimarchiveschangelogic.updatepersonfile;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PimArchivesChange pimarchiveschangeupdatepersonfiledefault;
global cn.ibizlab.ehr.core.pim.service.IPimArchivesChangeService pimarchiveschangeservice;
global cn.ibizlab.ehr.core.pim.service.IPimArchivesChangeService iBzSysPimarchiveschangeDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimarchiveschangeupdatepersonfilebegin"
    when
    then
    end

//逻辑处理节点[更新档案信息]
rule "deaction1"
ruleflow-group "pimarchiveschangeupdatepersonfiledeaction1"
    when
    then
    pimarchiveschangeservice.updatePersonFile(pimarchiveschangeupdatepersonfiledefault);
    update(pimarchiveschangeupdatepersonfiledefault);//更新fact中变量值
    end

