package cn.ibizlab.ehr.pim.logic.pimarchivesloanandreturnlogic.updatearchivestate;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PimArchiveSloanandreturn pimarchivesloanandreturnupdatearchivestatedefault;
global cn.ibizlab.ehr.core.pim.service.IPimArchiveSloanandreturnService pimarchivesloanandreturnservice;
global cn.ibizlab.ehr.core.pim.service.IPimArchiveSloanandreturnService iBzSysPimarchivesloanandreturnDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimarchivesloanandreturnupdatearchivestatebegin"
    when
    then
    end

//逻辑处理节点[更新档案信息归还状态]
rule "deaction1"
ruleflow-group "pimarchivesloanandreturnupdatearchivestatedeaction1"
    when
    then
    pimarchivesloanandreturnservice.updateArchiveState(pimarchivesloanandreturnupdatearchivestatedefault);
    update(pimarchivesloanandreturnupdatearchivestatedefault);//更新fact中变量值
    end

