package cn.ibizlab.ehr.pim.logic.pimbyzzjlmxlogic.setsxrq;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PIMBYZZJLMX pimbyzzjlmxsetsxrqdefault;
global cn.ibizlab.ehr.core.pim.service.IPIMBYZZJLMXService iBzSysPimbyzzjlmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[设置生效日期]
rule "prepareparam1"
ruleflow-group "pimbyzzjlmxsetsxrqprepareparam1"
    when
    then
    update(pimbyzzjlmxsetsxrqdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimbyzzjlmxsetsxrqbegin"
    when
    then
    end

