package cn.ibizlab.ehr.pim.logic.pimbyzzjlmxlogic.fillpersoninfo;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PimByzzjlmx pimbyzzjlmxfillpersoninfodefault;
global cn.ibizlab.ehr.core.pim.domain.PimPerson pimbyzzjlmxfillpersoninfopimperson;
global cn.ibizlab.ehr.core.pim.service.IPimPersonService pimpersonservice;
global cn.ibizlab.ehr.core.pim.service.IPimByzzjlmxService iBzSysPimbyzzjlmxDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimbyzzjlmxfillpersoninfobegin"
    when
    then
    end

//逻辑处理节点[填充人员信息]
rule "prepareparam2"
ruleflow-group "pimbyzzjlmxfillpersoninfoprepareparam2"
    when
    then
    pimbyzzjlmxfillpersoninfodefault.set("ygbh",pimbyzzjlmxfillpersoninfopimperson.get("ygbh"));
    pimbyzzjlmxfillpersoninfodefault.set("zz",pimbyzzjlmxfillpersoninfopimperson.get("ormorgname"));
    pimbyzzjlmxfillpersoninfodefault.set("zzid",pimbyzzjlmxfillpersoninfopimperson.get("ormorgid"));
    pimbyzzjlmxfillpersoninfodefault.set("bm",pimbyzzjlmxfillpersoninfopimperson.get("ormorgsectorname"));
    pimbyzzjlmxfillpersoninfodefault.set("bmid",pimbyzzjlmxfillpersoninfopimperson.get("ormorgsectorid"));
    pimbyzzjlmxfillpersoninfodefault.set("ybhqysj",pimbyzzjlmxfillpersoninfopimperson.get("ygbhqysj"));
    pimbyzzjlmxfillpersoninfodefault.set("yyglx",pimbyzzjlmxfillpersoninfopimperson.get("yglx"));
    update(pimbyzzjlmxfillpersoninfodefault);//更新fact中变量值
    update(pimbyzzjlmxfillpersoninfopimperson);//更新fact中变量值
    end

//逻辑处理节点[设置人员id]
rule "prepareparam1"
ruleflow-group "pimbyzzjlmxfillpersoninfoprepareparam1"
    when
    then
    pimbyzzjlmxfillpersoninfopimperson.set("pimpersonid",pimbyzzjlmxfillpersoninfodefault.get("pimpersonid"));
    update(pimbyzzjlmxfillpersoninfodefault);//更新fact中变量值
    update(pimbyzzjlmxfillpersoninfopimperson);//更新fact中变量值
    end

//逻辑处理节点[获取人员信息]
rule "deaction1"
ruleflow-group "pimbyzzjlmxfillpersoninfodeaction1"
    when
    then
    cn.ibizlab.ehr.util.helper.CachedBeanCopier.copy(pimpersonservice.get(pimbyzzjlmxfillpersoninfopimperson.getPimpersonid()),pimbyzzjlmxfillpersoninfopimperson);
    update(pimbyzzjlmxfillpersoninfodefault);//更新fact中变量值
    update(pimbyzzjlmxfillpersoninfopimperson);//更新fact中变量值
    end

