package cn.ibizlab.ehr.pim.logic.pimcontractlogic.calcontracttime;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PimContract pimcontractcalcontracttimedefault;
global cn.ibizlab.ehr.core.pim.service.IPimContractService pimcontractservice;
global cn.ibizlab.ehr.core.pim.service.IPimContractService iBzSysPimcontractDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[计算合同签订次数]
rule "deaction1"
ruleflow-group "pimcontractcalcontracttimedeaction1"
    when
    then
    pimcontractservice.calContractTime(pimcontractcalcontracttimedefault);
    update(pimcontractcalcontracttimedefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimcontractcalcontracttimebegin"
    when
    then
    end

