package cn.ibizlab.ehr.pim.logic.pimeducationlogic.checkhighestedu;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PIMEDUCATION pimeducationcheckhighestedudefault;
global cn.ibizlab.ehr.core.pim.service.IPIMEDUCATIONService pimeducationservice;
global cn.ibizlab.ehr.core.pim.service.IPIMEDUCATIONService iBzSysPimeducationDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[检查最高学历]
rule "deaction1"
ruleflow-group "pimeducationcheckhighestedudeaction1"
    when
    then
    pimeducationservice.checkHighestEdu(pimeducationcheckhighestedudefault);
    update(pimeducationcheckhighestedudefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimeducationcheckhighestedubegin"
    when
    then
    end

