package cn.ibizlab.ehr.pim.logic.pimfaminfologic.updatecontact;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PIMFAMINFO pimfaminfoupdatecontactdefault;
global cn.ibizlab.ehr.core.pim.service.IPIMFAMINFOService pimfaminfoservice;
global cn.ibizlab.ehr.core.pim.service.IPIMFAMINFOService iBzSysPimfaminfoDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[更新紧急联络人]
rule "deaction1"
ruleflow-group "pimfaminfoupdatecontactdeaction1"
    when
    then
    pimfaminfoservice.updateContact(pimfaminfoupdatecontactdefault);
    update(pimfaminfoupdatecontactdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimfaminfoupdatecontactbegin"
    when
    then
    end

