package cn.ibizlab.ehr.pim.logic.pimpersonlogic.genratepersonfile;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PimPerson pimpersongenratepersonfiledefault;
global cn.ibizlab.ehr.core.pim.service.IPimPersonService pimpersonservice;
global cn.ibizlab.ehr.core.pim.service.IPimPersonService iBzSysPimpersonDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimpersongenratepersonfilebegin"
    when
    then
    end

//逻辑处理节点[生成档案]
rule "deaction1"
ruleflow-group "pimpersongenratepersonfiledeaction1"
    when
    then
    pimpersonservice.generatePersonFile(pimpersongenratepersonfiledefault);
    update(pimpersongenratepersonfiledefault);//更新fact中变量值
    end

