package cn.ibizlab.ehr.pim.logic.pimrewardpunishmentlogic.generatefj;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PIMENCLOSURE pimrewardpunishmentgeneratefjenclosure;
global cn.ibizlab.ehr.core.pim.domain.PIMREWARDPUNISHMENT pimrewardpunishmentgeneratefjdefault;
global cn.ibizlab.ehr.core.pim.service.IPIMENCLOSUREService pimenclosureservice;
global cn.ibizlab.ehr.core.pim.service.IPIMREWARDPUNISHMENTService iBzSysPimrewardpunishmentDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[保存附件]
rule "deaction1"
ruleflow-group "pimrewardpunishmentgeneratefjdeaction1"
    when
    then
    pimenclosureservice.save(pimrewardpunishmentgeneratefjenclosure);
    update(pimrewardpunishmentgeneratefjenclosure);//更新fact中变量值
    update(pimrewardpunishmentgeneratefjdefault);//更新fact中变量值
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "pimrewardpunishmentgeneratefjprepareparam1"
    when
    then
    pimrewardpunishmentgeneratefjenclosure.set("enable",pimrewardpunishmentgeneratefjdefault.get("enable"));
    pimrewardpunishmentgeneratefjenclosure.set("fjkz",pimrewardpunishmentgeneratefjdefault.get("fj"));
    pimrewardpunishmentgeneratefjenclosure.set("fj",pimrewardpunishmentgeneratefjdefault.get("fj"));
    pimrewardpunishmentgeneratefjenclosure.set("pimpersonid",pimrewardpunishmentgeneratefjdefault.get("pimpersonid"));
    pimrewardpunishmentgeneratefjenclosure.set("pimpersonname",pimrewardpunishmentgeneratefjdefault.get("pimpersonname"));
    pimrewardpunishmentgeneratefjenclosure.set("pimenclosureid",pimrewardpunishmentgeneratefjdefault.get("pimrewardpunishmentid"));
    pimrewardpunishmentgeneratefjenclosure.set("pimenclosurename",pimrewardpunishmentgeneratefjdefault.get("pimrewardpunishmentname"));
    pimrewardpunishmentgeneratefjenclosure.set("fjfl","90");
    update(pimrewardpunishmentgeneratefjenclosure);//更新fact中变量值
    update(pimrewardpunishmentgeneratefjdefault);//更新fact中变量值
    end

//逻辑处理节点[逻辑删除]
rule "prepareparam2"
ruleflow-group "pimrewardpunishmentgeneratefjprepareparam2"
    when
    then
    pimrewardpunishmentgeneratefjenclosure.set("enable","0");
    update(pimrewardpunishmentgeneratefjenclosure);//更新fact中变量值
    update(pimrewardpunishmentgeneratefjdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimrewardpunishmentgeneratefjbegin"
    when
    then
    end

