package cn.ibizlab.ehr.pim.logic.pimtitlelogic.ensurehighesttech;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.pim.domain.PIMTITLE pimtitleensurehighesttechdefault;
global cn.ibizlab.ehr.core.pim.service.IPIMTITLEService pimtitleservice;
global cn.ibizlab.ehr.core.pim.service.IPIMTITLEService iBzSysPimtitleDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "pimtitleensurehighesttechbegin"
    when
    then
    end

//逻辑处理节点[确认唯一最高职称]
rule "deaction1"
ruleflow-group "pimtitleensurehighesttechdeaction1"
    when
    then
    pimtitleservice.ensureHighestTech(pimtitleensurehighesttechdefault);
    update(pimtitleensurehighesttechdefault);//更新fact中变量值
    end

