package cn.ibizlab.ehr.sal.logic.salschemeitemlogic.setordernum;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.sal.domain.SalSchemeItem salschemeitemsetordernumdefault;
global cn.ibizlab.ehr.core.sal.service.ISalSchemeItemService iBzSysSalschemeitemDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "salschemeitemsetordernumbegin"
    when
    then
    end

//逻辑处理节点[设置默认排序]
rule "rawsqlcall1"
ruleflow-group "salschemeitemsetordernumrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",salschemeitemsetordernumdefault.get("salitemid"));
    String strSql="select XH  as XH from T_SALITEM where SALITEMID=#{et.param0} and enable=1";
    java.util.List<JSONObject> entities=iBzSysSalschemeitemDefaultService.select(strSql,param);//SQL调用
    if(entities.size()>0){
        JSONObject entity=entities.get(0);
        for (Map.Entry entry : entity.entrySet()) {
            salschemeitemsetordernumdefault.set(String.valueOf(entry.getKey()),entry.getValue());
        }
    }
    update(salschemeitemsetordernumdefault);//更新fact中变量值
    end

