package cn.ibizlab.ehr.soc.logic.socarchiveslogic.stoparchives;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.soc.domain.SocArchives socarchivesstoparchivesdefault;
global cn.ibizlab.ehr.core.soc.service.ISocArchivesService socarchivesservice;
global cn.ibizlab.ehr.core.soc.service.ISocArchivesService iBzSysSocarchivesDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[失效档案]
rule "deaction1"
ruleflow-group "socarchivesstoparchivesdeaction1"
    when
    then
    socarchivesservice.update(socarchivesstoparchivesdefault);
    update(socarchivesstoparchivesdefault);//更新fact中变量值
    end

//逻辑处理节点[准备参数]
rule "prepareparam1"
ruleflow-group "socarchivesstoparchivesprepareparam1"
    when
    then
    socarchivesstoparchivesdefault.set("state","20");
    update(socarchivesstoparchivesdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "socarchivesstoparchivesbegin"
    when
    then
    end

