package cn.ibizlab.ehr.soc.logic.socrulelogic.initruledetail;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.soc.domain.SocRule socruleinitruledetaildefault;
global cn.ibizlab.ehr.core.soc.service.ISocRuleService iBzSysSocruleDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "socruleinitruledetailbegin"
    when
    then
    end

//逻辑处理节点[初始化明细]
rule "rawsqlcall1"
ruleflow-group "socruleinitruledetailrawsqlcall1"
    when
    then
    Map param =new HashMap();
    param.put("param0",socruleinitruledetaildefault.get("socruleid"));
    String strSql="INSERT INTO T_SOCRULEDETAIL  (SOCRULEDETAILID,CREATEMAN,CREATEDATE,UPDATEMAN,UPDATEDATE,SOCTYPEID,SOCRULEID) SELECT CONCAT(T.SOCRULEID,T1.SOCTYPEID),T.UPDATEMAN,T.UPDATEDATE,T.UPDATEMAN,T.UPDATEDATE,T1.SOCTYPEID,T.SOCRULEID  FROM T_SOCRULE T LEFT OUTER JOIN T_SOCTYPE T1 ON 1=1 WHERE T.SOCRULEID=#{et.param0} AND T1.ENABLE=1  AND NOT EXISTS(SELECT 1 FROM T_SOCRULEDETAIL A WHERE A.SOCRULEID=T.SOCRULEID AND A.SOCTYPEID=T1.SOCTYPEID)";
    iBzSysSocruleDefaultService.execute(strSql,param);//SQL调用
    update(socruleinitruledetaildefault);//更新fact中变量值
    end

