package cn.ibizlab.ehr.trm.logic.trmdutycadreslogic.updatesatetesx;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.trm.domain.TrmDutyCadres trmdutycadresupdatesatetesxdefault;
global cn.ibizlab.ehr.core.trm.service.ITrmDutyCadresService trmdutycadresservice;
global cn.ibizlab.ehr.core.trm.service.ITrmDutyCadresService iBzSysTrmdutycadresDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[更新状态（生效）]
rule "prepareparam1"
ruleflow-group "trmdutycadresupdatesatetesxprepareparam1"
    when
    then
    trmdutycadresupdatesatetesxdefault.set("status","10");
    update(trmdutycadresupdatesatetesxdefault);//更新fact中变量值
    end

//逻辑处理节点[更新]
rule "deaction1"
ruleflow-group "trmdutycadresupdatesatetesxdeaction1"
    when
    then
    trmdutycadresservice.update(trmdutycadresupdatesatetesxdefault);
    update(trmdutycadresupdatesatetesxdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "trmdutycadresupdatesatetesxbegin"
    when
    then
    end

