package cn.ibizlab.ehr.trm.logic.trmtrainplantermlogic.qx;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.trm.domain.TrmTrainPlanterm trmtrainplantermqxdefault;
global cn.ibizlab.ehr.core.trm.service.ITrmTrainPlantermService trmtrainplantermservice;
global cn.ibizlab.ehr.core.trm.service.ITrmTrainPlantermService iBzSysTrmtrainplantermDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[更新状态]
rule "deaction1"
ruleflow-group "trmtrainplantermqxdeaction1"
    when
    then
    trmtrainplantermservice.update(trmtrainplantermqxdefault);
    update(trmtrainplantermqxdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "trmtrainplantermqxbegin"
    when
    then
    end

//逻辑处理节点[参数准备]
rule "prepareparam1"
ruleflow-group "trmtrainplantermqxprepareparam1"
    when
    then
    trmtrainplantermqxdefault.set("bjzt","40");
    update(trmtrainplantermqxdefault);//更新fact中变量值
    end

