package cn.ibizlab.ehr.trm.logic.trmtrainplanlogic.setrejectstatus;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.trm.domain.TrmTrainPlan trmtrainplansetrejectstatusdefault;
global cn.ibizlab.ehr.core.trm.service.ITrmTrainPlanService trmtrainplanservice;
global cn.ibizlab.ehr.core.trm.service.ITrmTrainPlanService iBzSysTrmtrainplanDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[更新状态]
rule "deaction1"
ruleflow-group "trmtrainplansetrejectstatusdeaction1"
    when
    then
    trmtrainplanservice.update(trmtrainplansetrejectstatusdefault);
    update(trmtrainplansetrejectstatusdefault);//更新fact中变量值
    end

//逻辑处理节点[参数准备]
rule "prepareparam1"
ruleflow-group "trmtrainplansetrejectstatusprepareparam1"
    when
    then
    trmtrainplansetrejectstatusdefault.set("approvalstatus","4");
    update(trmtrainplansetrejectstatusdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "trmtrainplansetrejectstatusbegin"
    when
    then
    end

