package cn.ibizlab.ehr.trm.logic.trmtrainplanlogic.setapprovalstatus;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.trm.domain.TrmTrainPlan trmtrainplansetapprovalstatusdefault;
global cn.ibizlab.ehr.core.trm.service.ITrmTrainPlanService trmtrainplanservice;
global cn.ibizlab.ehr.core.trm.service.ITrmTrainPlanService iBzSysTrmtrainplanDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[参数准备]
rule "prepareparam1"
ruleflow-group "trmtrainplansetapprovalstatusprepareparam1"
    when
    then
    trmtrainplansetapprovalstatusdefault.set("approvalstatus","3");
    update(trmtrainplansetapprovalstatusdefault);//更新fact中变量值
    end

//逻辑处理节点[更新状态]
rule "deaction1"
ruleflow-group "trmtrainplansetapprovalstatusdeaction1"
    when
    then
    trmtrainplanservice.update(trmtrainplansetapprovalstatusdefault);
    update(trmtrainplansetapprovalstatusdefault);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "trmtrainplansetapprovalstatusbegin"
    when
    then
    end

