package cn.ibizlab.ehr.common.logic.userlogic.createrelatedinfo;

import java.util.Map;
import java.util.HashMap;
import com.alibaba.fastjson.JSONObject;
global cn.ibizlab.ehr.core.common.domain.MsgAccount usercreaterelatedinfomsgaccount;
global cn.ibizlab.ehr.core.common.domain.User usercreaterelatedinfodefault;
global cn.ibizlab.ehr.core.wf.domain.WFUser usercreaterelatedinfowfuser;
global cn.ibizlab.ehr.core.common.service.IMsgAccountService msgaccountservice;
global cn.ibizlab.ehr.core.wf.service.IWFUserService wfuserservice;
global cn.ibizlab.ehr.core.common.service.IUserService iBzSysUserDefaultService;
global cn.ibizlab.ehr.util.security.AuthenticationUser curuser;

no-loop

//逻辑处理节点[准备流程用户对象]
rule "prepareparam1"
ruleflow-group "usercreaterelatedinfoprepareparam1"
    when
    then
    usercreaterelatedinfowfuser.set("wfuserid",usercreaterelatedinfodefault.get("userid"));
    usercreaterelatedinfowfuser.set("wfusername",usercreaterelatedinfodefault.get("username"));
    usercreaterelatedinfowfuser.set("validflag",usercreaterelatedinfodefault.get("validflag"));
    update(usercreaterelatedinfomsgaccount);//更新fact中变量值
    update(usercreaterelatedinfodefault);//更新fact中变量值
    update(usercreaterelatedinfowfuser);//更新fact中变量值
    end

//逻辑处理节点[准备消息账户对象]
rule "prepareparam2"
ruleflow-group "usercreaterelatedinfoprepareparam2"
    when
    then
    usercreaterelatedinfomsgaccount.set("msgaccountid",usercreaterelatedinfodefault.get("userid"));
    usercreaterelatedinfomsgaccount.set("msgaccountname",usercreaterelatedinfodefault.get("username"));
    usercreaterelatedinfomsgaccount.set("islist","0");
    update(usercreaterelatedinfomsgaccount);//更新fact中变量值
    update(usercreaterelatedinfodefault);//更新fact中变量值
    update(usercreaterelatedinfowfuser);//更新fact中变量值
    end

//逻辑处理节点[建立消息账户]
rule "deaction2"
ruleflow-group "usercreaterelatedinfodeaction2"
    when
    then
    msgaccountservice.save(usercreaterelatedinfomsgaccount);
    update(usercreaterelatedinfomsgaccount);//更新fact中变量值
    update(usercreaterelatedinfodefault);//更新fact中变量值
    update(usercreaterelatedinfowfuser);//更新fact中变量值
    end

//逻辑处理节点[建立流程用户]
rule "deaction1"
ruleflow-group "usercreaterelatedinfodeaction1"
    when
    then
    wfuserservice.save(usercreaterelatedinfowfuser);
    update(usercreaterelatedinfomsgaccount);//更新fact中变量值
    update(usercreaterelatedinfodefault);//更新fact中变量值
    update(usercreaterelatedinfowfuser);//更新fact中变量值
    end

//逻辑处理节点[开始]
rule "begin"
ruleflow-group "usercreaterelatedinfobegin"
    when
    then
    end

