server:
  port: 6097
#zuul网关路由设置
zuul:
  routes:
    salscheme:
      path: /salschemes/**
      serviceId: ehr-webapi
      stripPrefix: false
    salruledetail:
      path: /salruledetails/**
      serviceId: ehr-webapi
      stripPrefix: false
    salrule:
      path: /salrules/**
      serviceId: ehr-webapi
      stripPrefix: false
    salsource:
      path: /salsources/**
      serviceId: ehr-webapi
      stripPrefix: false
    salparam:
      path: /salparams/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormorg:
      path: /ormorgs/**
      serviceId: ehr-webapi
      stripPrefix: false
    salsubject:
      path: /salsubjects/**
      serviceId: ehr-webapi
      stripPrefix: false
    saltype:
      path: /saltypes/**
      serviceId: ehr-webapi
      stripPrefix: false
    salitem:
      path: /salitems/**
      serviceId: ehr-webapi
      stripPrefix: false
    salschemeitem:
      path: /salschemeitems/**
      serviceId: ehr-webapi
      stripPrefix: false
    codelist:
      path: /codelist1s/**
      serviceId: ehr-webapi
      stripPrefix: false
    salstdgwgz:
      path: /salstdgwgzs/**
      serviceId: ehr-webapi
      stripPrefix: false
    salstdxmgz:
      path: /salstdxmgzs/**
      serviceId: ehr-webapi
      stripPrefix: false
    ormduty:
      path: /ormduties/**
      serviceId: ehr-webapi
      stripPrefix: false
    codeitem:
      path: /codeitems/**
      serviceId: ehr-webapi
      stripPrefix: false
  sensitive-headers:
    - Cookie,Set-Cookie,Authorization
