version: "3.2"
services:
  ehr-app-ehrpim:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ehr-app-ehrpim:latest
    ports:
      - "6097:6097"
    networks:
      - agent_network
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.16.240.110
      - SERVER_PORT=6097
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=172.16.240.110:8848
      - SPRING_REDIS_HOST=172.16.100.243
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0
      - SPRING_DATASOURCE_USERNAME=a_LAB01_bd0ca3178
      - SPRING_DATASOURCE_PASSWORD=25A3@0@a
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.186.185:3306/a_LAB01_bd0ca3178?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_DEFAULTSCHEMA=a_LAB01_bd0ca3178
      - CAS=https://passport.ibizlab.cn
      - NACOS=172.16.240.110:8848
    deploy:
      resources:
           limits:
               memory: 800M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1
    volumes:
      - "nfs:/app/file"

volumes:
  nfs:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=172.16.240.109,rw"
      device: ":/nfs"

networks:
  agent_network:
    driver: overlay
    attachable: true

