version: "3.2"
services:
  ehr-app-ehrpim:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ehr-app-ehrpim:latest
    ports:
      - "8080:8080"
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true

