version: "3.2"
services:
  ehr-provider-wfcallback:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ehr-provider-wfcallback:latest
    ports:
      - "8081:8081"
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true