version: "3.2"
services:
  ehr-provider-webapi:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ehr-provider-webapi:latest
    ports:
      - "8081:8081"
    networks:
      - agent_network
    deploy:
      resources:
           limits:
               memory: 4048M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true

