version: "3.2"
services:
  ehr-app-ehrorm:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ehr-app-ehrorm:latest
    ports:
      - "8080:8080"
    networks:
      - agent_network
    deploy:
      resources:
           limits:
               memory: 800M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true

