version: "3.2"
services:
  ehr-app-ehrpcm2:
    image: registry.cn-shanghai.aliyuncs.com/ibizsys/ehr-app-ehrpcm2:latest
    ports:
      - "36092:36092"
    networks:
      - agent_network
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_IP=172.16.240.110
      - SERVER_PORT=36092
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=172.16.240.110:38848
      - SPRING_REDIS_HOST=172.16.100.243
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_DATABASE=0
      - SPRING_DATASOURCE_USERNAME=a_LAB01_fb710d59e
      - SPRING_DATASOURCE_PASSWORD=bD@@681@
      - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.186.185:3306/a_LAB01_fb710d59e?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.jdbc.Driver
      - SPRING_DATASOURCE_DEFAULTSCHEMA=a_LAB01_fb710d59e
      - CAS=https://passport.ibizlab.cn
      - NACOS=172.16.240.110:38848
    deploy:
      resources:
           limits:
               memory: 800M
           reservations:
               memory: 400M    
      mode: replicated
      replicas: 1

networks:
  agent_network:
    driver: overlay
    attachable: true

